// --- Helper для автоматического перевода названий языков ---
const ruNames: Record<string, string> = {
    'en': 'Английский', 'ru': 'Русский', 'es': 'Испанский', 'fr': 'Французский',
    'de': 'Немецкий', 'zh': 'Китайский', 'uk': 'Украинский', 'pl': 'Польский',
    'ar': 'Арабский', 'ja': 'Японский', 'ko': 'Корейский', 'pt': 'Португальский',
    'it': 'Итальянский', 'tr': 'Турецкий', 'hi': 'Хинди', 'he': 'Иврит',
    'nl': 'Голландский', 'sv': 'Шведский', 'fi': 'Финский', 'no': 'Норвежский',
    'da': 'Датский', 'cs': 'Чешский', 'el': 'Греческий', 'hu': 'Венгерский',
    'ro': 'Румынский', 'id': 'Индонезийский', 'th': 'Тайский', 'vi': 'Вьетнамский',
    'bn': 'Бенгальский', 'fa': 'Персидский'
};

export const getLanguageName = (langCode: string, uiLang: string): string => {
    try {
        const cleanCode = langCode.trim().toLowerCase().split('-')[0];

        // Жесткая привязка полных названий для русского интерфейса
        if (uiLang === 'ru' && ruNames[cleanCode]) {
            return ruNames[cleanCode];
        }

        const displayNames = new Intl.DisplayNames([uiLang], {type: 'language'});
        const name = displayNames.of(cleanCode);
        if (name) {
            return name.charAt(0).toUpperCase() + name.slice(1);
        }
    } catch (e) {
        console.error("Language translation error", e);
    }

    // Фолбек
    const fallback = availableLanguages.find(l => l.code.toLowerCase() === langCode.toLowerCase().trim())?.name;
    return fallback || langCode.toUpperCase();
};

// --- Translation Dictionary ---
export const translations = {
    ar: {
        enterWord: 'أدخل الكلمة...',
        translation: 'الترجمة...',
        cefrHint: 'مستويات CEFR الرسمية: من A1 (مبتدئ) إلى C2 (متقدم).',
        usageHint: 'وتيرة الاستخدام في الحياة اليومية: من 1 (نادر) إلى 10 (شائع).',
        examples: 'أمثلة',
        synonyms: 'مرادفات',
        explanation: 'تفسير',
        chooseLang: 'اختر',
        examplesContent: 'ستظهر هنا أمثلة من الحياة الواقعية لمساعدتك على فهم السياق.',
        synonymsContent: 'ستظهر هنا قائمة بالمرادفات المفيدة لإثراء مفرداتك.',
        explanationContent: 'ستظهر هنا التفسيرات التفصيلية والأصول والقواعد النحوية.',
        selectTargetWarning: 'يرجى تحديد لغة الترجمة أولاً',
        sourceOptional: 'تلقائي',
        resetLanguage: 'إعادة تعيين',
        loading: 'جارٍ الترجمة...',
        translateBtn: 'ترجمة',
        save: 'حفظ',
        menuDictionaries: 'قواميس',
        menuPrices: 'الأسعار والمميزات',
        menuChangeLang: 'تغيير اللغة',
        menuLogout: 'تسجيل الخروج',
        menuRemoveProfile: 'حذف الحساب',
        confirmTitle: 'هل أنت متأكد؟',
        confirmLogoutText: 'سيتم تسجيل خروجك من الحساب.',
        confirmRemoveText: 'سيؤدي هذا الإجراء إلى حذف ملفك الشخصي وجميع القواميس نهائيًا.',
        btnCancel: 'إلغاء',
        btnConfirm: 'نعم',
        saveToDict: 'حفظ الكلمة',
        noDicts: 'لم تقم بإنشاء أي قواميس حتى الآن.',
        btnCreateDict: 'إنشاء قاموس',
        selectDict: 'اختر قاموسًا أو أنشئ واحدًا جديدًا',
        authTitle: 'مرحباً',
        authSubtitle: 'قم بتسجيل الدخول لاستخدام الترجمات والقواميس',
        authBtn: 'تسجيل الدخول باستخدام Google',
        authLoading: 'جاري الاتصال...',
        planFree: 'خطة مجانية',
        month: 'شهر',
        day: 'يوم',
        requests: 'طلبات الذكاء الاصطناعي',
        currentPlan: 'الخطة الحالية',
        upgradeBtn: 'ترقية',
        hintAi: 'اعتمادًا على نموذج الذكاء الاصطناعي، ستتلقى إجابات بجودة وعمق مختلفين.',
        hintReq: 'يؤثر عدد الطلبات على عدد الكلمات التي يمكنك ترجمتها يوميًا.',
        textTooLong: 'النص طويل جدًا',
        fullTranslations: 'ترجمات كاملة',
        quickTranslations: 'ترجمات سريعة',
        resetAt: 'تتم إعادة التعيين في',
        limitReached: 'تم الوصول إلى الحد. انتظر إعادة التعيين.',
        dictLimit: 'تم الوصول إلى حد القاموس.',
        wordLimit: 'تم الوصول إلى حد الكلمات المحفوظة.',
        donateText: 'هل تريد المساعدة في جعل AiTerm أفضل؟ يمكنك دعم المشروع بتبرع. هذا ليس إلزامياً، ولكنه محل تقدير دائماً! ❤️',
        supportBtn: 'دعم AiTerm',
        limitModalTitle: 'تم الوصول إلى الحد',
        limitModalRequests: 'لقد وصلت إلى حد طلبات الترجمة الخاصة بك. يرجى الانتظار حتى يتم إعادة ضبط المؤقت.',
        limitModalDicts: 'لقد وصلت إلى الحد الأقصى لعدد القواميس.',
        limitModalWords: 'لقد وصلت إلى الحد الأقصى للكلمات المحفوظة.',
        btnCloseModal: 'إغلاق',
        serverBusy: 'خوادم الذكاء الاصطناعي محملة بشكل زائد. يرجى المحاولة بعد بضع ثوانٍ.',
        networkError: 'خطأ في الشبكة. تحقق من اتصالك.',
        genericError: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
        duplicateWarningText: 'هذه الكلمة موجودة بالفعل في القاموس \'{dictName}\'. هل أنت متأكد أنك تريد حفظها؟',
        btnYesAdd: 'نعم، أضف',
        welcomeTitle: 'مرحبًا بك في AiTerm 1.0! 🎉',
        welcomeText1: 'هذه إضافة مجانية تمامًا. تحصل على 30 طلبًا يوميًا للنافذة الرئيسية و 30 للنافذة المصغرة.',
        welcomeText2: 'تم بناء المشروع بشغف. إذا وجدته مفيدًا، يمكنك دعم المؤلف في الإعدادات!',
        welcomeBtn: 'لننطلق!',
        about_menu: 'حول AiTerm',
        btnRenameDict: 'إعادة تسمية القاموس',
        sessionExpired: 'انتهت الجلسة. سجل الدخول مرة أخرى.',
        dictCreated: 'تم إنشاء القاموس',
        failedToCreate: 'فشل الإنشاء',
        dictRenamed: 'تمت إعادة تسمية القاموس',
        failedToRename: 'فشلت إعادة التسمية',
        nothingToSave: 'لا شيء للحفظ',
        savedSuccessfully: 'تم الحفظ بنجاح',
        failedToSave: 'فشل الحفظ',
        profileDeleted: 'تم حذف الحساب',
        failedToDeleteProfile: 'فشل حذف الحساب',
        dictDeleted: 'تم حذف القاموس',
        failedToDelete: 'فشل الحذف',
        wordDeleted: 'تم حذف الكلمة',
        loginSuccessful: 'تم تسجيل الدخول بنجاح',
        serverError: 'خطأ في الخادم',
        loginCancelled: 'تم إلغاء تسجيل الدخول',
        translateWordFirst: 'ترجم كلمة أولاً',
        gibberishError: 'فشل التعرف على النص',
        notLoggedIn: 'غير مسجل الدخول',
        logInBtn: 'تسجيل الدخول',
        settingsFeatures: 'الإعدادات والميزات',
        payCards: 'ادفع بالبطاقات من أي مكان في العالم: Visa, Mastercard, Apple Pay, Google Pay',
        quickTransPopup: 'نافذة الترجمة السريعة',
        quickTransDesc: 'إظهار زر AiTerm عائم عند تحديد نص في أي صفحة ويب.',
        soonBadge: 'المزيد من الميزات الرائعة قادمة في التحديثات المستقبلية! 🚀',
        aboutTitle1: 'ما هو AiTerm؟',
        aboutText1: 'AiTerm هو مساعد ترجمة متقدم يعمل بالذكاء الاصطناعي، مصمم للتحليل السياقي العميق وتسريع تعلم اللغة.',
        aboutTitle2: 'لماذا تختار AiTerm؟',
        aboutText2: '• الدقة السياقية: تجاوز الترجمات الحرفية. يحلل AiTerm النص المحيط لتقديم المعنى الأنسب.\n• تقييم CEFR: حدد مستوى صعوبة أي كلمة فوراً.\n• قواميس ذكية: ابنِ مفرداتك الخاصة عن طريق حفظ الكلمات مع سياقها الكامل.',
        aboutTitle3: 'كيفية الاستخدام',
        aboutText3: '1. ترجمة: أدخل مصطلحاً، اختر لغة الهدف، واضغط على "ترجمة".\n2. حفظ: انقر على أيقونة "حفظ" لإضافة الكلمة إلى مجموعتك.\n3. إدارة: نظم مفرداتك عبر قائمة "القواميس".',
        devContacts: 'جهات اتصال المطور',
        searchDict: 'البحث في القواميس...',
        searchWord: 'البحث عن كلمة...',
        noWordsSaved: 'لم يتم حفظ أي كلمات بعد.',
        nothingFound: 'لم يتم العثور على شيء.',
        confirmDeleteDict: 'هل تريد حذف هذا القاموس وجميع كلماته نهائياً؟',
        confirmDeleteWord: 'هل تريد حذف هذه الكلمة نهائياً؟',
        confirmDuplicateDict: 'يوجد قاموس بهذا الاسم مسبقاً. هل تريد إنشاؤه على أي حال؟',
        dictNamePlaceholder: 'اسم القاموس...',
        btnCreate: 'إنشاء',
        btnRename: 'إعادة تسمية',
        newNamePlaceholder: 'الاسم الجديد...',
        emailCopied: 'تم نسخ البريد الإلكتروني',
        version: 'الإصدار 1.0'
    },
    zh: {
        enterWord: '输入单词...',
        translation: '翻译...',
        cefrHint: '官方 CEFR 语言级别：从 A1（初学者）到 C2（精通）。',
        usageHint: '日常生活中单词的使用频率：从 1（罕见）到 10（常见）。',
        examples: '例句',
        synonyms: '同义词',
        explanation: '解释',
        chooseLang: '选择',
        examplesContent: '现实生活中的例句将显示在这里，帮助您理解上下文。',
        synonymsContent: '这里将显示有用的同义词列表，以丰富您的词汇量。',
        explanationContent: '该单词的详细解释、起源和语法规则将显示在此处。',
        selectTargetWarning: '请先选择翻译语言',
        sourceOptional: '自动',
        resetLanguage: '重置',
        loading: '翻译中...',
        translateBtn: '翻译',
        save: '保存',
        menuDictionaries: '词典',
        menuPrices: '价格与高级版',
        menuChangeLang: '更改语言',
        menuLogout: '登出',
        menuRemoveProfile: '删除资料',
        confirmTitle: '你确定吗？',
        confirmLogoutText: '您将从您的账户中注销。',
        confirmRemoveText: '此操作将永久删除您的个人资料和所有词典。',
        btnCancel: '取消',
        btnConfirm: '是的',
        saveToDict: '保存单词',
        noDicts: '您还没有创建任何字典。',
        btnCreateDict: '创建字典',
        selectDict: '选择字典或创建新字典',
        authTitle: '欢迎',
        authSubtitle: '登录以使用翻译和词典',
        authBtn: '使用 Google 登录',
        authLoading: '连接中...',
        planFree: '免费计划',
        month: '月',
        day: '天',
        requests: 'AI 请求',
        currentPlan: '当前计划',
        upgradeBtn: '升级',
        hintAi: '根据您选择的 AI 模型，您将获得不同质量和深度的答案。',
        hintReq: '查询次数会影响您每天可以翻译的单词数量。',
        textTooLong: '文本太长',
        fullTranslations: '完整翻译',
        quickTranslations: '快速翻译',
        resetAt: '重置于',
        limitReached: '达到限制。等待重置。',
        dictLimit: '达到词典限制。',
        wordLimit: '保存单词的限制已达到。',
        donateText: '想帮助 AiTerm 变得更好吗？您可以通过捐赠来支持该项目。这不是必须的，但我们始终深表感激！❤️',
        supportBtn: '支持 AiTerm',
        limitModalTitle: '达到限制',
        limitModalRequests: '您已达到翻译请求限制。请等待计时器重置。',
        limitModalDicts: '您已达到最大词典数量。',
        limitModalWords: '您已达到保存单词的最大数量。',
        btnCloseModal: '关闭',
        serverBusy: 'AI 服务器过载。请几秒钟后再试。',
        networkError: '网络错误。请检查您的连接。',
        genericError: '发生错误。请重试。',
        duplicateWarningText: '此单词已存在于词典 \'{dictName}\' 中。确定要保存吗？',
        btnYesAdd: '是的，添加',
        welcomeTitle: '欢迎使用 AiTerm 1.0! 🎉',
        welcomeText1: '这是一个完全免费的扩展程序。您每天有 30 次主窗口请求和 30 次迷你窗口请求。',
        welcomeText2: '这个项目是充满热情的结晶。如果您觉得有用，可以在设置中支持作者！',
        welcomeBtn: '开始使用！',
        about_menu: '关于 AiTerm',
        btnRenameDict: '重名词典',
        sessionExpired: '会话已过期。请重新登录。',
        dictCreated: '词典已创建',
        failedToCreate: '创建失败',
        dictRenamed: '词典已重命名',
        failedToRename: '重命名失败',
        nothingToSave: '没有要保存的内容',
        savedSuccessfully: '保存成功',
        failedToSave: '保存失败',
        profileDeleted: '个人资料已删除',
        failedToDeleteProfile: '删除资料失败',
        dictDeleted: '词典已删除',
        failedToDelete: '删除失败',
        wordDeleted: '单词已删除',
        loginSuccessful: '登录成功',
        serverError: '服务器错误',
        loginCancelled: '登录已取消',
        translateWordFirst: '请先翻译一个单词',
        gibberishError: '无法识别文本',
        notLoggedIn: '未登录',
        logInBtn: '登录',
        settingsFeatures: '设置与功能',
        payCards: '使用世界各地的银行卡支付：Visa、Mastercard、Apple Pay、Google Pay',
        quickTransPopup: '快速翻译弹窗',
        quickTransDesc: '在网页上选中文本时显示浮动的 AiTerm 按钮。',
        soonBadge: '未来的更新中将推出更多激动人心的功能！🚀',
        aboutTitle1: '什么是 AiTerm？',
        aboutText1: 'AiTerm 是一款先进的人工智能翻译助手，专为深度上下文分析和加速语言学习而设计。',
        aboutTitle2: '为什么选择 AiTerm？',
        aboutText2: '• 上下文准确性：超越字面翻译。AiTerm 分析周围文本以提供最相关的含义。\n• CEFR 评估：即时识别任何单词的难度级别。\n• 智能词典：通过保存单词及其完整上下文来构建您的个人词汇表。',
        aboutTitle3: '如何使用',
        aboutText3: '1. 翻译：输入术语，选择目标语言并点击“翻译”。\n2. 保存：点击“保存”图标将单词添加到您的收藏中。\n3. 管理：通过“词典”菜单组织您的词汇。',
        devContacts: '开发者联系方式',
        searchDict: '搜索词典...',
        searchWord: '搜索单词...',
        noWordsSaved: '暂未保存任何单词。',
        nothingFound: '未找到结果。',
        confirmDeleteDict: '永久删除此词典及其所有单词？',
        confirmDeleteWord: '永久删除此单词？',
        confirmDuplicateDict: '已存在同名词典。确定要创建吗？',
        dictNamePlaceholder: '词典名称...',
        btnCreate: '创建',
        btnRename: '重命名',
        newNamePlaceholder: '新名称...',
        emailCopied: '已复制电子邮件',
        version: '版本 1.0'
    },
    en: {
        enterWord: 'Enter word...',
        translation: 'Translation...',
        cefrHint: 'Official CEFR language levels: from A1 (beginner) to C2 (fluent).',
        usageHint: 'Frequency of word usage in daily life: from 1 (rare) to 10 (common).',
        examples: 'Examples',
        synonyms: 'Synonyms',
        explanation: 'Explanation',
        chooseLang: 'Select',
        examplesContent: 'Real-life examples will appear here to help you understand the context.',
        synonymsContent: 'A list of useful synonyms will appear here to enrich your vocabulary.',
        explanationContent: 'Detailed explanations, origins, and grammar rules for this word will be shown here.',
        selectTargetWarning: 'Please select a translation language first',
        sourceOptional: 'Auto',
        resetLanguage: 'Reset',
        loading: 'Translating...',
        translateBtn: 'Translate',
        save: 'Save',
        menuDictionaries: 'Dictionaries',
        menuPrices: 'Prices & Premium',
        menuChangeLang: 'Change Language',
        menuLogout: 'Log out',
        menuRemoveProfile: 'Remove profile',
        confirmTitle: 'Are you sure?',
        confirmLogoutText: 'You will be logged out of your account.',
        confirmRemoveText: 'This action will permanently delete your profile and all dictionaries.',
        btnCancel: 'Cancel',
        btnConfirm: 'Yes, do it',
        saveToDict: 'Save Word',
        noDicts: 'You haven\'t created any dictionaries yet.',
        btnCreateDict: 'Create dictionary',
        selectDict: 'Select a dictionary or create a new one',
        authTitle: 'Welcome',
        authSubtitle: 'Sign in to use translations and dictionaries',
        authBtn: 'Sign in with Google',
        authLoading: 'Connecting...',
        planFree: 'Free plan',
        month: 'month',
        day: 'day',
        requests: 'AI requests',
        currentPlan: 'Current plan',
        upgradeBtn: 'Upgrade',
        hintAi: 'Depending on the AI model you select, you will receive answers of different quality and depth.',
        hintReq: 'The number of queries affects how many words you can translate per day.',
        textTooLong: 'Text is too long',
        fullTranslations: 'Full translations',
        quickTranslations: 'Quick translations',
        resetAt: 'Resets at',
        limitReached: 'Limit reached. Wait for reset.',
        dictLimit: 'Dictionary limit reached.',
        wordLimit: 'Saved words limit reached.',
        donateText: 'Want to help AiTerm get even better? You can support the project with a custom donation. It’s never required, but always deeply appreciated! ❤️',
        supportBtn: 'Support AiTerm',
        limitModalTitle: 'Limit Reached',
        limitModalRequests: 'You have reached your translation requests limit. Please wait for the timer to reset.',
        limitModalDicts: 'You have reached the maximum number of dictionaries.',
        limitModalWords: 'You have reached the maximum number of saved words.',
        btnCloseModal: 'Close',
        serverBusy: 'AI servers are overloaded. Please try again in a few seconds.',
        networkError: 'Network error. Check your internet connection.',
        genericError: 'An error occurred. Please try again.',
        duplicateWarningText: 'This word already exists in the dictionary \'{dictName}\'. Are you sure you want to save it?',
        btnYesAdd: 'Yes, add',
        welcomeTitle: 'Welcome to AiTerm 1.0! 🎉',
        welcomeText1: 'This is a completely free extension. You get 30 requests daily for the main window and 30 for the mini-window.',
        welcomeText2: 'The project is built with passion. If you find it useful, you can support the author in the menu!',
        welcomeBtn: 'Let\'s Go!',
        about_menu: 'About AiTerm',
        btnRenameDict: 'Rename dictionary',
        sessionExpired: 'Session expired. Log in again.',
        dictCreated: 'Dictionary created',
        failedToCreate: 'Failed to create',
        dictRenamed: 'Dictionary renamed',
        failedToRename: 'Failed to rename',
        nothingToSave: 'Nothing to save',
        savedSuccessfully: 'Saved successfully',
        failedToSave: 'Failed to save',
        profileDeleted: 'Profile deleted',
        failedToDeleteProfile: 'Failed to delete profile',
        dictDeleted: 'Dictionary deleted',
        failedToDelete: 'Failed to delete',
        wordDeleted: 'Word deleted',
        loginSuccessful: 'Login successful',
        serverError: 'Server error',
        loginCancelled: 'Login cancelled',
        translateWordFirst: 'Translate a word first',
        gibberishError: 'Failed to recognize text',
        notLoggedIn: 'Not logged in',
        logInBtn: 'Log in',
        settingsFeatures: 'Settings & Features',
        payCards: 'Pay with cards from anywhere in the world: Visa, Mastercard, Apple Pay, Google Pay',
        quickTransPopup: 'Quick Translation Popup',
        quickTransDesc: 'Show a floating AiTerm button when you select text on any webpage.',
        soonBadge: 'More exciting features coming in future updates! 🚀',
        aboutTitle1: 'What is AiTerm?',
        aboutText1: 'AiTerm is an advanced, AI-powered translation assistant designed for deep contextual analysis and accelerated language learning.',
        aboutTitle2: 'Why choose AiTerm?',
        aboutText2: '• Contextual Accuracy: Move beyond literal translations. AiTerm analyzes the surrounding text to provide the most relevant meaning.\n• CEFR Assessment: Instantly identify the difficulty level of any word.\n• Smart Dictionaries: Build your personal vocabulary by saving words along with their full context.',
        aboutTitle3: 'How to use',
        aboutText3: '1. Translate: Enter a term, select your target language, and click "Translate".\n2. Save: Click the "Save" icon to add a word to your collection.\n3. Manage: Access and organize your vocabulary via the "Dictionaries" menu.',
        devContacts: 'Developer Contacts',
        searchDict: 'Search dictionary...',
        searchWord: 'Search word...',
        noWordsSaved: 'No words saved yet.',
        nothingFound: 'Nothing found.',
        confirmDeleteDict: 'Delete this dictionary and all its words permanently?',
        confirmDeleteWord: 'Delete this word permanently?',
        confirmDuplicateDict: 'A dictionary with this name already exists. Create anyway?',
        dictNamePlaceholder: 'Dictionary name...',
        btnCreate: 'Create',
        btnRename: 'Rename',
        newNamePlaceholder: 'New name...',
        emailCopied: 'Email copied to clipboard',
        version: 'Version 1.0'
    },
    fr: {
        enterWord: 'Entrez un mot...',
        translation: 'Traduction...',
        cefrHint: 'Niveaux de langue officiels du CECRL : de A1 (débutant) à C2 (bilingue).',
        usageHint: 'Fréquence d\'utilisation du mot au quotidien : de 1 (rare) à 10 (courant).',
        examples: 'Exemples',
        synonyms: 'Synonymes',
        explanation: 'Explication',
        chooseLang: 'Choisir',
        examplesContent: 'Des exemples de la vie réelle apparaîtront ici pour vous aider à comprendre le contexte.',
        synonymsContent: 'Une liste de synonymes utiles apparaîtra ici pour enrichir votre vocabulaire.',
        explanationContent: 'Des explications détaillées, les origines et les règles de grammaire seront affichées ici.',
        selectTargetWarning: 'Veuillez d\'abord choisir une langue de traduction',
        sourceOptional: 'Auto',
        resetLanguage: 'Réinitialiser',
        loading: 'Traduction...',
        translateBtn: 'Traduire',
        save: 'Sauver',
        menuDictionaries: 'Dictionnaires',
        menuPrices: 'Prix & Premium',
        menuChangeLang: 'Changer de langue',
        menuLogout: 'Se déconnecter',
        menuRemoveProfile: 'Supprimer le profil',
        confirmTitle: 'Êtes-vous sûr ?',
        confirmLogoutText: 'Vous serez déconnecté de votre compte.',
        confirmRemoveText: 'Cette action supprimera définitivement votre profil et tous vos dictionnaires.',
        btnCancel: 'Annuler',
        btnConfirm: 'Oui',
        saveToDict: 'Enregistrer le mot',
        noDicts: 'Vous n\'avez pas encore créé de dictionnaire.',
        btnCreateDict: 'Créer un dictionnaire',
        selectDict: 'Sélectionnez un dictionnaire ou créez-en un',
        authTitle: 'Bienvenue',
        authSubtitle: 'Connectez-vous pour utiliser les traductions et les dictionnaires',
        authBtn: 'Se connecter avec Google',
        authLoading: 'Connexion...',
        planFree: 'Plan gratuit',
        month: 'mois',
        day: 'jour',
        requests: 'Requêtes IA',
        currentPlan: 'Plan actuel',
        upgradeBtn: 'Mettre à niveau',
        hintAi: 'Selon le modèle d\'IA que vous sélectionnez, vous recevrez des réponses de qualité et de profondeur différentes.',
        hintReq: 'Le nombre de requêtes affecte le nombre de mots que vous pouvez traduire par jour.',
        textTooLong: 'Le texte est trop long',
        fullTranslations: 'Traduções complètes',
        quickTranslations: 'Traductions rapides',
        resetAt: 'Réinitialisation à',
        limitReached: 'Limite atteinte. Attendez la réinitialisation.',
        dictLimit: 'Limite de dictionnaires atteinte.',
        wordLimit: 'Limite de mots enregistrés atteinte.',
        donateText: 'Vous voulez aider AiTerm à s\'améliorer ? Vous pouvez soutenir le projet avec un don. Ce n\'est jamais obligatoire, mais toujours apprécié ! ❤️',
        supportBtn: 'Soutenir AiTerm',
        limitModalTitle: 'Limite Atteinte',
        limitModalRequests: 'Vous avez atteint votre limite de requêtes. Veuillez attendre la réinitialisation du minuteur.',
        limitModalDicts: 'Vous avez atteint le nombre maximum de dictionnaires.',
        limitModalWords: 'Vous avez atteint le nombre maximum de mots enregistrés.',
        btnCloseModal: 'Fermer',
        serverBusy: 'Les serveurs IA sont surchargés. Réessayez dans quelques secondes.',
        networkError: 'Erreur réseau. Vérifiez votre connexion internet.',
        genericError: 'Une erreur s\'est produite. Veuillez réessayer.',
        duplicateWarningText: 'Ce mot existe déjà dans le dictionnaire \'{dictName}\'. Êtes-vous sûr de vouloir l\'enregistrer ?',
        btnYesAdd: 'Oui, ajouter',
        welcomeTitle: 'Bienvenue sur AiTerm 1.0 ! 🎉',
        welcomeText1: 'Il s\'agit d\'une extension entièrement gratuite. Vous obtenez 30 requêtes par jour pour la fenêtre principale et 30 pour la mini-fenêtre.',
        welcomeText2: 'Ce projet a été créé avec passion. Si vous le trouvez utile, vous pouvez soutenir l\'auteur dans le menu !',
        welcomeBtn: 'C\'est parti !',
        about_menu: 'À propos d\'AiTerm',
        btnRenameDict: 'Renommer le dictionnaire',
        sessionExpired: 'Session expirée. Reconnectez-vous.',
        dictCreated: 'Dictionnaire créé',
        failedToCreate: 'Échec de la création',
        dictRenamed: 'Dictionnaire renommé',
        failedToRename: 'Échec du renommage',
        nothingToSave: 'Rien à sauvegarder',
        savedSuccessfully: 'Sauvegardé avec succès',
        failedToSave: 'Échec de la sauvegarde',
        profileDeleted: 'Profil supprimé',
        failedToDeleteProfile: 'Échec de la suppression du profil',
        dictDeleted: 'Dictionnaire supprimé',
        failedToDelete: 'Échec de la suppression',
        wordDeleted: 'Mot supprimé',
        loginSuccessful: 'Connexion réussie',
        serverError: 'Erreur du serveur',
        loginCancelled: 'Connexion annulée',
        translateWordFirst: 'Traduisez d\'abord un mot',
        gibberishError: 'Impossible de reconnaître le texte',
        notLoggedIn: 'Non connecté',
        logInBtn: 'Se connecter',
        settingsFeatures: 'Paramètres & Fonctionnalités',
        payCards: 'Payez par carte depuis le monde entier : Visa, Mastercard, Apple Pay, Google Pay',
        quickTransPopup: 'Fenêtre de traduction rapide',
        quickTransDesc: 'Afficher un bouton AiTerm flottant lorsque vous sélectionnez du texte sur n\'importe quelle page Web.',
        soonBadge: 'Plus de fonctionnalités passionnantes à venir dans les futures mises à jour ! 🚀',
        aboutTitle1: 'Qu\'est-ce qu\'AiTerm ?',
        aboutText1: 'AiTerm est un assistant de traduction avancé propulsé par l\'IA, conçu pour une analyse contextuelle profonde.',
        aboutTitle2: 'Pourquoi choisir AiTerm ?',
        aboutText2: '• Précision contextuelle : Au-delà de la traduction littérale. AiTerm analyse le texte environnant.\n• Évaluation CECRL : Identifiez le niveau de difficulté d\'un mot.\n• Dictionnaires intelligents : Créez votre vocabulaire en enregistrant des mots avec leur contexte complet.',
        aboutTitle3: 'Comment l\'utiliser',
        aboutText3: '1. Traduire : Entrez un terme, choisissez la langue cible et cliquez sur "Traduire".\n2. Enregistrer : Cliquez sur l\'icône "Sauver" pour ajouter un mot.\n3. Gérer : Organisez votre vocabulaire via le menu "Dictionnaires".',
        devContacts: 'Contacts du développeur',
        searchDict: 'Rechercher un dictionnaire...',
        searchWord: 'Rechercher un mot...',
        noWordsSaved: 'Aucun mot enregistré pour le moment.',
        nothingFound: 'Aucun résultat.',
        confirmDeleteDict: 'Supprimer ce dictionnaire et tous ses mots définitivement ?',
        confirmDeleteWord: 'Supprimer ce mot définitivement ?',
        confirmDuplicateDict: 'Un dictionnaire avec ce nom existe déjà. Le créer quand même ?',
        dictNamePlaceholder: 'Nom du dictionnaire...',
        btnCreate: 'Créer',
        btnRename: 'Renommer',
        newNamePlaceholder: 'Nouveau nom...',
        emailCopied: 'E-mail copié',
        version: 'Version 1.0'
    },
    hi: {
        enterWord: 'शब्द दर्ज करें...',
        translation: 'अनुवाद...',
        cefrHint: 'आधिकारिक CEFR भाषा स्तर: A1 (शुरुआती) से C2 (प्रवाहपूर्ण) तक।',
        usageHint: 'दैनिक जीवन में शब्द के उपयोग की आवृत्ति: 1 (दुर्लभ) से 10 (सामान्य) तक।',
        examples: 'उदाहरण',
        synonyms: 'पर्यायवाची',
        explanation: 'व्याख्या',
        chooseLang: 'चुनें',
        examplesContent: 'संदर्भ को पूरी तरह से समझने में आपकी मदद करने के लिए वास्तविक जीवन के उदाहरण यहां दिखाई देंगे।',
        synonymsContent: 'आपकी दैनिक शब्दावली को समृद्ध करने के लिए उपयोगी पर्यायवाची शब्दों की सूची यहां दिखाई देगी।',
        explanationContent: 'इस शब्द के लिए विस्तृत स्पष्टीकरण, उत्पत्ति और व्याकरण के नियम यहां दिखाए जाएंगे।',
        selectTargetWarning: 'कृपया पहले अनुवाद की भाषा चुनें',
        sourceOptional: 'स्वत:',
        resetLanguage: 'रीसेट',
        loading: 'अनुवाद...',
        translateBtn: 'अनुवाद',
        save: 'सहेजें',
        menuDictionaries: 'शब्दकोश',
        menuPrices: 'कीमतें और प्रीमियम',
        menuChangeLang: 'भाषा बदलें',
        menuLogout: 'लॉग आउट',
        menuRemoveProfile: 'प्रोफ़ाइल हटाएं',
        confirmTitle: 'क्या आप सुनिश्चित हैं?',
        confirmLogoutText: 'आप अपने खाते से लॉग आउट हो जाएंगे।',
        confirmRemoveText: 'यह क्रिया आपके प्रोफ़ाइल और सभी शब्दकोशों को स्थायी रूप से हटा देगी।',
        btnCancel: 'रद्द करें',
        btnConfirm: 'हां',
        saveToDict: 'शब्द सहेजें',
        noDicts: 'आपने अभी तक कोई शब्दकोश नहीं बनाया है।',
        btnCreateDict: 'शब्दकोश बनाएं',
        selectDict: 'शब्दकोश चुनें या नया बनाएं',
        authTitle: 'स्वागत है',
        authSubtitle: 'अनुवाद और शब्दकोशों का उपयोग करने के लिए साइन इन करें',
        authBtn: 'Google के साथ साइन इन करें',
        authLoading: 'कनेक्ट हो रहा है...',
        planFree: 'मुफ़्त योजना',
        month: 'महीना',
        day: 'दिन',
        requests: 'AI अनुरोध',
        currentPlan: 'वर्तमान योजना',
        upgradeBtn: 'अपग्रेड',
        hintAi: 'आपके द्वारा चुने गए AI मॉडल के आधार पर, आपको अलग-अलग गुणवत्ता के उत्तर प्राप्त होंगे।',
        hintReq: 'प्रश्नों की संख्या इस बात को प्रभावित करती है कि आप प्रतिदिन कितने शब्दों का अनुवाद कर सकते हैं।',
        textTooLong: 'टेक्स्ट बहुत लंबा है',
        fullTranslations: 'पूर्ण अनुवाद',
        quickTranslations: 'त्वरित अनुवाद',
        resetAt: 'रीसेट का समय',
        limitReached: 'सीमा पूरी हो गई। रीसेट की प्रतीक्षा करें।',
        dictLimit: 'शब्दकोश की सीमा पूरी हो गई।',
        wordLimit: 'सहेजे गए शब्दों की सीमा पूरी हो गई।',
        donateText: 'क्या आप AiTerm को और बेहतर बनाने में मदद करना चाहते हैं? आप दान के साथ इस प्रोजेक्ट का समर्थन कर सकते हैं। यह आवश्यक नहीं है, लेकिन हमेशा सराहा जाता है! ❤️',
        supportBtn: 'AiTerm का समर्थन करें',
        limitModalTitle: 'सीमा पूरी हो गई',
        limitModalRequests: 'आप अनुवाद अनुरोध की सीमा तक पहुँच गए हैं। कृपया टाइमर के रीसेट होने की प्रतीक्षा करें।',
        limitModalDicts: 'आप शब्दकोशों की अधिकतम संख्या तक पहुँच गए हैं।',
        limitModalWords: 'आप सहेजे गए शब्दों की अधिकतम संख्या तक पहुँच गए हैं।',
        btnCloseModal: 'बंद करें',
        serverBusy: 'AI सर्वर व्यस्त हैं। कुछ सेकंड बाद पुनः प्रयास करें।',
        networkError: 'नेटवर्क त्रुटि। अपना कनेक्शन जांचें।',
        genericError: 'कोई त्रुटि हुई। कृपया पुनः प्रयास करें।',
        duplicateWarningText: 'यह शब्द \'{dictName}\' में पहले से मौजूद है। क्या आप निश्चित रूप से इसे सहेजना चाहते हैं?',
        btnYesAdd: 'हाँ, जोड़ें',
        welcomeTitle: 'AiTerm 1.0 में आपका स्वागत है! 🎉',
        welcomeText1: 'यह पूरी तरह से मुफ़्त एक्सटेंशन है। आपको मुख्य विंडो के लिए प्रतिदिन 30 और मिनी-विंडो के लिए 30 अनुरोध मिलते हैं।',
        welcomeText2: 'यह प्रोजेक्ट उत्साह के साथ बनाया गया है। यदि आपको यह उपयोगी लगता है, तो आप सेटिंग में लेखक का समर्थन कर सकते हैं!',
        welcomeBtn: 'शुरू करें!',
        about_menu: 'AiTerm के बारे में',
        btnRenameDict: 'शब्दकोश का नाम बदलें',
        sessionExpired: 'सत्र समाप्त हो गया। फिर से लॉग इन करें।',
        dictCreated: 'शब्दकोश बनाया गया',
        failedToCreate: 'बनाने में विफल',
        dictRenamed: 'शब्दकोश का नाम बदला गया',
        failedToRename: 'नाम बदलने में विफल',
        nothingToSave: 'सहेजने के लिए कुछ नहीं',
        savedSuccessfully: 'सफलतापूर्वक सहेजा गया',
        failedToSave: 'सहेजने में विफल',
        profileDeleted: 'प्रोफ़ाइल हटाई गई',
        failedToDeleteProfile: 'प्रोफ़ाइल हटाने में विफल',
        dictDeleted: 'शब्दकोश हटाया गया',
        failedToDelete: 'हटाने में विफल',
        wordDeleted: 'शब्द हटाया गया',
        loginSuccessful: 'लॉगिन सफल',
        serverError: 'सर्वर त्रुटि',
        loginCancelled: 'लॉगिन रद्द किया गया',
        translateWordFirst: 'पहले किसी शब्द का अनुवाद करें',
        gibberishError: 'टेक्स्ट को पहचानने में विफल',
        notLoggedIn: 'लॉग इन नहीं है',
        logInBtn: 'लॉग इन करें',
        settingsFeatures: 'सेटिंग्स और सुविधाएँ',
        payCards: 'दुनिया भर से कार्ड से भुगतान करें: Visa, Mastercard, Apple Pay, Google Pay',
        quickTransPopup: 'त्वरित अनुवाद पॉपअप',
        quickTransDesc: 'वेबपेज पर टेक्स्ट चुनने पर फ्लोटिंग AiTerm बटन दिखाएं।',
        soonBadge: 'भविष्य के अपडेट में और अधिक रोमांचक सुविधाएँ आ रही हैं! 🚀',
        aboutTitle1: 'AiTerm क्या है?',
        aboutText1: 'AiTerm एक उन्नत, AI-संचालित अनुवाद सहायक है जिसे संदर्भ विश्लेषण के लिए डिज़ाइन किया गया है।',
        aboutTitle2: 'AiTerm क्यों चुनें?',
        aboutText2: '• प्रासंगिक सटीकता: केवल शाब्दिक अनुवाद नहीं।\n• CEFR मूल्यांकन: तुरंत कठिनाई स्तर पहचानें।\n• स्मार्ट शब्दकोश: शब्दों को संदर्भ के साथ सहेजें।',
        aboutTitle3: 'कैसे उपयोग करें',
        aboutText3: '1. अनुवाद करें: एक शब्द दर्ज करें और लक्ष्य भाषा चुनें।\n2. सहेजें: संग्रह में शब्द जोड़ने के लिए "सहेजें" पर क्लिक करें।\n3. प्रबंधित करें: अपने शब्दकोश को व्यवस्थित करें।',
        devContacts: 'डेवलपर संपर्क',
        searchDict: 'शब्दकोश खोजें...',
        searchWord: 'शब्द खोजें...',
        noWordsSaved: 'अभी तक कोई शब्द नहीं सहेजा गया।',
        nothingFound: 'कुछ नहीं मिला।',
        confirmDeleteDict: 'इस शब्दकोश और इसके सभी शब्दों को स्थायी रूप से हटाएं?',
        confirmDeleteWord: 'इस शब्द को स्थायी रूप से हटाएं?',
        confirmDuplicateDict: 'इस नाम का शब्दकोश पहले से मौजूद है। फिर भी बनाएं?',
        dictNamePlaceholder: 'शब्दकोश का नाम...',
        btnCreate: 'बनाएं',
        btnRename: 'नाम बदलें',
        newNamePlaceholder: 'नया नाम...',
        emailCopied: 'ईमेल कॉपी किया गया',
        version: 'संस्करण 1.0'
    },
    pl: {
        enterWord: 'Wpisz słowo...',
        translation: 'Tłumaczenie...',
        cefrHint: 'Oficjalne poziomy biegłości językowej CEFR: od A1 (początkujący) do C2 (biegły).',
        usageHint: 'Częstotliwość użycia słowa w życiu codziennym: od 1 (rzadko) do 10 (często).',
        examples: 'Przykłady',
        synonyms: 'Synonimy',
        explanation: 'Wyjaśnienie',
        chooseLang: 'Wybierz',
        examplesContent: 'Pojawią się tu przykłady z życia wzięte, aby pomóc ci zrozumieć kontekst.',
        synonymsContent: 'Tutaj pojawi się lista przydatnych synonimów, które wzbogacą twoje słownictwo.',
        explanationContent: 'Tutaj wyświetlone zostaną szczegółowe wyjaśnienia i zasady gramatyczne dla tego słowa.',
        selectTargetWarning: 'Proszę najpierw wybrać język tłumaczenia',
        sourceOptional: 'Auto',
        resetLanguage: 'Resetuj',
        loading: 'Tłumaczenie...',
        translateBtn: 'Tłumacz',
        save: 'Zapisz',
        menuDictionaries: 'Słowniki',
        menuPrices: 'Ceny i Premium',
        menuChangeLang: 'Zmień język',
        menuLogout: 'Wyloguj',
        menuRemoveProfile: 'Usuń profil',
        confirmTitle: 'Jesteś pewien?',
        confirmLogoutText: 'Zostaniesz wylogowany ze swojego konta.',
        confirmRemoveText: 'Ta akcja trwale usunie Twój profil i wszystkie słowniki.',
        btnCancel: 'Anuluj',
        btnConfirm: 'Tak',
        saveToDict: 'Zapisz słowo',
        noDicts: 'Nie utworzyłeś jeszcze żadnych słowników.',
        btnCreateDict: 'Utwórz słownik',
        selectDict: 'Wybierz słownik lub utwórz nowy',
        authTitle: 'Witamy',
        authSubtitle: 'Zaloguj się, aby korzystać z tłumaczeń i słowników',
        authBtn: 'Zaloguj się przez Google',
        authLoading: 'Łączenie...',
        planFree: 'Darmowy plan',
        month: 'miesiąc',
        day: 'dzień',
        requests: 'Zapytania AI',
        currentPlan: 'Obecny plan',
        upgradeBtn: 'Ulepsz',
        hintAi: 'W zależności od wybranego modelu AI otrzymasz odpowiedzi o różnej jakości i głębi.',
        hintReq: 'Liczba zapytań wpływa na to, ile słów możesz przetłumaczyć dziennie.',
        textTooLong: 'Tekst jest za długi',
        fullTranslations: 'Pełne tłumaczenia',
        quickTranslations: 'Szybkie tłumaczenia',
        resetAt: 'Reset o',
        limitReached: 'Limit wyczerpany.',
        dictLimit: 'Osiągnięto limit słowników.',
        wordLimit: 'Osiągnięto limit zapisanych słów.',
        donateText: 'Chcesz pomóc w ulepszaniu AiTerm? Możesz wesprzeć projekt donacją. Nie jest to wymagane, ale zawsze doceniane! ❤️',
        supportBtn: 'Wesprzyj AiTerm',
        limitModalTitle: 'Limit osiągnięty',
        limitModalRequests: 'Osiągnąłeś limit zapytań o tłumaczenie. Poczekaj na reset timera.',
        limitModalDicts: 'Osiągnąłeś maksymalną liczbę słowników.',
        limitModalWords: 'Osiągnąłeś maksymalną liczbę zapisanych słów.',
        btnCloseModal: 'Zamknij',
        serverBusy: 'Serwery AI są przeciążone. Spróbuj ponownie za kilka sekund.',
        networkError: 'Błąd sieci. Sprawdź swoje połączenie.',
        genericError: 'Wystąpił błąd. Spróbuj ponownie.',
        duplicateWarningText: 'To słowo już istnieje w słowniku \'{dictName}\'. Czy na pewno chcesz je zapisać?',
        btnYesAdd: 'Tak, dodaj',
        welcomeTitle: 'Witamy w AiTerm 1.0! 🎉',
        welcomeText1: 'To całkowicie darmowe rozszerzenie. Otrzymujesz 30 zapytań dziennie do głównego okna i 30 do mini-okna.',
        welcomeText2: 'Projekt powstaje z pasji. Jeśli uznasz go za przydatny, możesz wesprzeć autora w ustawieniach!',
        welcomeBtn: 'Zaczynamy!',
        about_menu: 'O AiTerm',
        btnRenameDict: 'Zmień nazwę słownika',
        sessionExpired: 'Sesja wygasła. Zaloguj się ponownie.',
        dictCreated: 'Słownik utworzony',
        failedToCreate: 'Nie udało się utworzyć',
        dictRenamed: 'Nazwa zmieniona',
        failedToRename: 'Nie udało się zmienić nazwy',
        nothingToSave: 'Nie ma nic do zapisania',
        savedSuccessfully: 'Zapisano pomyślnie',
        failedToSave: 'Nie udało się zapisać',
        profileDeleted: 'Profil usunięty',
        failedToDeleteProfile: 'Nie udało się usunąć profilu',
        dictDeleted: 'Słownik usunięty',
        failedToDelete: 'Nie udało się usunąć',
        wordDeleted: 'Słowo usunięte',
        loginSuccessful: 'Logowanie udane',
        serverError: 'Błąd serwera',
        loginCancelled: 'Logowanie anulowane',
        translateWordFirst: 'Najpierw przetłumacz słowo',
        gibberishError: 'Nie udało się rozpoznać tekstu',
        notLoggedIn: 'Niezalogowany',
        logInBtn: 'Zaloguj się',
        settingsFeatures: 'Ustawienia i funkcje',
        payCards: 'Płać kartą z dowolnego miejsca na świecie: Visa, Mastercard, Apple Pay, Google Pay',
        quickTransPopup: 'Szybkie tłumaczenie Popup',
        quickTransDesc: 'Pokaż pływający przycisk AiTerm po zaznaczeniu tekstu na stronie.',
        soonBadge: 'Więcej funkcji już wkrótce! 🚀',
        aboutTitle1: 'Czym jest AiTerm?',
        aboutText1: 'AiTerm to zaawansowany asystent tłumacza oparty na AI, stworzony do głębokiej analizy kontekstu.',
        aboutTitle2: 'Dlaczego AiTerm?',
        aboutText2: '• Dokładność kontekstowa: Więcej niż dosłowne tłumaczenie.\n• Ocena CEFR: Sprawdź trudność słowa.\n• Inteligentne słowniki: Zapisuj słowa z całym ich kontekstem.',
        aboutTitle3: 'Jak używać',
        aboutText3: '1. Tłumacz: Wpisz słowo, wybierz język i kliknij "Tłumacz".\n2. Zapisz: Użyj ikony "Zapisz", by dodać do słownika.\n3. Zarządzaj: Organizuj swoje słowa w menu.',
        devContacts: 'Kontakt z deweloperem',
        searchDict: 'Szukaj słownika...',
        searchWord: 'Szukaj słowa...',
        noWordsSaved: 'Brak zapisanych słów.',
        nothingFound: 'Nic nie znaleziono.',
        confirmDeleteDict: 'Usunąć ten słownik i wszystkie jego słowa bezpowrotnie?',
        confirmDeleteWord: 'Usunąć to słowo bezpowrotnie?',
        confirmDuplicateDict: 'Słownik o tej nazwie już istnieje. Utworzyć mimo to?',
        dictNamePlaceholder: 'Nazwa słownika...',
        btnCreate: 'Utwórz',
        btnRename: 'Zmień nazwę',
        newNamePlaceholder: 'Nowa nazwa...',
        emailCopied: 'Skopiowano email',
        version: 'Wersja 1.0'
    },
    pt: {
        enterWord: 'Digite a palavra...',
        translation: 'Tradução...',
        cefrHint: 'Níveis oficiais de idiomas do CEFR: de A1 (iniciante) a C2 (fluente).',
        usageHint: 'Frequência de uso da palavra no dia a dia: de 1 (raro) a 10 (comum).',
        examples: 'Exemplos',
        synonyms: 'Sinônimos',
        explanation: 'Explicação',
        chooseLang: 'Escolher',
        examplesContent: 'Exemplos da vida real aparecerão aqui para ajudar você a entender o contexto.',
        synonymsContent: 'Uma lista de sinônimos úteis aparecerá aqui para enriquecer seu vocabulário.',
        explanationContent: 'Explicações detalhadas, origens e regras gramaticais para esta palavra serão mostradas aqui.',
        selectTargetWarning: 'Por favor, selecione um idioma de tradução primeiro',
        sourceOptional: 'Auto',
        resetLanguage: 'Redefinir',
        loading: 'Traduzindo...',
        translateBtn: 'Traduzir',
        save: 'Salvar',
        menuDictionaries: 'Dicionários',
        menuPrices: 'Preços e Premium',
        menuChangeLang: 'Mudar idioma',
        menuLogout: 'Sair',
        menuRemoveProfile: 'Remover perfil',
        confirmTitle: 'Tem certeza?',
        confirmLogoutText: 'Você será desconectado da sua conta.',
        confirmRemoveText: 'Esta ação excluirá permanentemente seu perfil e todos os dicionários.',
        btnCancel: 'Cancelar',
        btnConfirm: 'Sim',
        saveToDict: 'Salvar Palavra',
        noDicts: 'Você ainda não criou nenhum dicionário.',
        btnCreateDict: 'Criar dicionário',
        selectDict: 'Selecione um dicionário ou crie um novo',
        authTitle: 'Bem-vindo',
        authSubtitle: 'Faça login para usar traduções e dicionários',
        authBtn: 'Fazer login com o Google',
        authLoading: 'Conectando...',
        planFree: 'Plano grátis',
        month: 'mês',
        day: 'dia',
        requests: 'Solicitações de IA',
        currentPlan: 'Plano atual',
        upgradeBtn: 'Atualizar',
        hintAi: 'Dependendo do modelo de IA selecionado, você receberá respostas de diferentes qualidades.',
        hintReq: 'O número de consultas afeta quantas palavras você pode traduzir por dia.',
        textTooLong: 'O texto é muito longo',
        fullTranslations: 'Traduções completas',
        quickTranslations: 'Traduções rápidas',
        resetAt: 'Reinicia às',
        limitReached: 'Limite atingido. Aguarde.',
        dictLimit: 'Limite de dicionários atingido.',
        wordLimit: 'Limite de palavras salvas atingido.',
        donateText: 'Quer ajudar o AiTerm a melhorar? Você pode apoiar o projeto com uma doação. Nunca é obrigatório, mas sempre apreciado! ❤️',
        supportBtn: 'Apoiar AiTerm',
        limitModalTitle: 'Limite Atingido',
        limitModalRequests: 'Você atingiu o limite de solicitações de tradução. Aguarde a redefinição.',
        limitModalDicts: 'Você atingiu o número máximo de dicionários.',
        limitModalWords: 'Você atingiu o número máximo de palavras salvas.',
        btnCloseModal: 'Fechar',
        serverBusy: 'Os servidores de IA estão sobrecarregados. Tente novamente em alguns segundos.',
        networkError: 'Erro de rede. Verifique sua conexão.',
        genericError: 'Ocorreu um erro. Tente novamente.',
        duplicateWarningText: 'Esta palavra já existe no dicionário \'{dictName}\'. Tem certeza de que deseja salvá-la?',
        btnYesAdd: 'Sim, adicionar',
        welcomeTitle: 'Bem-vindo ao AiTerm 1.0! 🎉',
        welcomeText1: 'Esta é uma extensão totalmente gratuita. Você recebe 30 solicitações diárias para a janela principal e 30 para a minijanela.',
        welcomeText2: 'O projeto é feito com paixão. Se achar útil, você pode apoiar o autor nas configurações!',
        welcomeBtn: 'Vamos lá!',
        about_menu: 'Sobre o AiTerm',
        btnRenameDict: 'Renomear dicionário',
        sessionExpired: 'A sessão expirou. Faça login novamente.',
        dictCreated: 'Dicionário criado',
        failedToCreate: 'Falha ao criar',
        dictRenamed: 'Dicionário renomeado',
        failedToRename: 'Falha ao renomear',
        nothingToSave: 'Nada para salvar',
        savedSuccessfully: 'Salvo com sucesso',
        failedToSave: 'Falha ao salvar',
        profileDeleted: 'Perfil excluído',
        failedToDeleteProfile: 'Falha ao excluir o perfil',
        dictDeleted: 'Dicionário excluído',
        failedToDelete: 'Falha ao excluir',
        wordDeleted: 'Palavra excluída',
        loginSuccessful: 'Login bem-sucedido',
        serverError: 'Erro no servidor',
        loginCancelled: 'Login cancelado',
        translateWordFirst: 'Traduza uma palavra primeiro',
        gibberishError: 'Falha ao reconhecer o texto',
        notLoggedIn: 'Não logado',
        logInBtn: 'Entrar',
        settingsFeatures: 'Configurações e Recursos',
        payCards: 'Pague com cartões de qualquer lugar do mundo: Visa, Mastercard, Apple Pay, Google Pay',
        quickTransPopup: 'Popup de tradução rápida',
        quickTransDesc: 'Exibir um botão flutuante AiTerm ao selecionar um texto em qualquer página da web.',
        soonBadge: 'Mais recursos empolgantes em breve nas futuras atualizações! 🚀',
        aboutTitle1: 'O que é o AiTerm?',
        aboutText1: 'O AiTerm é um assistente de tradução avançado focado na análise de contexto profundo.',
        aboutTitle2: 'Por que o AiTerm?',
        aboutText2: '• Precisão contextual: Além das traduções literais.\n• Avaliação do CEFR: Identifique a dificuldade da palavra.\n• Dicionários inteligentes: Construa seu vocabulário pessoal.',
        aboutTitle3: 'Como usar',
        aboutText3: '1. Traduzir: Digite a palavra, escolha o idioma e clique em Traduzir.\n2. Salvar: Clique no ícone de salvar.\n3. Gerenciar: Use o menu de Dicionários.',
        devContacts: 'Contatos do desenvolvedor',
        searchDict: 'Buscar dicionário...',
        searchWord: 'Buscar palavra...',
        noWordsSaved: 'Nenhuma palavra salva ainda.',
        nothingFound: 'Nada encontrado.',
        confirmDeleteDict: 'Excluir este dicionário e todas as suas palavras permanentemente?',
        confirmDeleteWord: 'Excluir esta palavra permanentemente?',
        confirmDuplicateDict: 'Um dicionário com esse nome já existe. Criar mesmo assim?',
        dictNamePlaceholder: 'Nome do dicionário...',
        btnCreate: 'Criar',
        btnRename: 'Renommer',
        newNamePlaceholder: 'Novo nome...',
        emailCopied: 'E-mail copiado',
        version: 'Versão 1.0'
    },
    ru: {
        enterWord: 'Введите слово...',
        translation: 'Перевод...',
        cefrHint: 'Официальная шкала уровней CEFR: от A1 (начинающий) до C2 (продвинутый).',
        usageHint: 'Частота использования слова в повседневной речи: от 1 (редко) до 10 (часто).',
        examples: 'Примеры',
        synonyms: 'Синонимы',
        explanation: 'Объяснение',
        chooseLang: 'Выбрать',
        examplesContent: 'Здесь появятся реальные примеры из жизни для понимания контекста.',
        synonymsContent: 'Здесь появится список полезных синонимов для обогащения словарного запаса.',
        explanationContent: 'Здесь будут показаны подробные объяснения и грамматические правила.',
        selectTargetWarning: 'Сначала выберите язык перевода',
        sourceOptional: 'Авто',
        resetLanguage: 'Сбросить',
        loading: 'Перевожу...',
        translateBtn: 'Перевести',
        save: 'Сохранить',
        menuDictionaries: 'Словари',
        menuPrices: 'Цены и Premium',
        menuChangeLang: 'Сменить язык',
        menuLogout: 'Выйти',
        menuRemoveProfile: 'Удалить профиль',
        confirmTitle: 'Вы уверены?',
        confirmLogoutText: 'Вы выйдете из своего аккаунта.',
        confirmRemoveText: 'Это действие навсегда удалит ваш профиль и все словари.',
        btnCancel: 'Отмена',
        btnConfirm: 'Да',
        saveToDict: 'Сохранить слово',
        noDicts: 'Вы еще не создали ни одного словаря.',
        btnCreateDict: 'Создать словарь',
        selectDict: 'Выберите словарь или создайте новый',
        authTitle: 'Добро пожаловать',
        authSubtitle: 'Войдите, чтобы использовать переводы и словари',
        authBtn: 'Войти через Google',
        authLoading: 'Подключение...',
        planFree: 'Бесплатный план',
        month: 'месяц',
        day: 'день',
        requests: 'AI запросы',
        currentPlan: 'Текущий план',
        upgradeBtn: 'Улучшить',
        hintAi: 'Выбранная ИИ-модель влияет на качество и глубину получаемого перевода.',
        hintReq: 'Количество запросов определяет, сколько слов вы можете перевести за день.',
        textTooLong: 'Слишком длинный текст',
        fullTranslations: 'Полные переводы',
        quickTranslations: 'Быстрые переводы',
        resetAt: 'Обновление в',
        limitReached: 'Лимит исчерпан. Дождитесь обновления.',
        dictLimit: 'Лимит словарей исчерпан.',
        wordLimit: 'Лимит сохраненных слов исчерпан.',
        donateText: 'Хочешь помочь AiTerm стать еще лучше? Ты можешь поддержать проект донатом. Это не обязательно, но всегда очень ценится! ❤️',
        supportBtn: 'Поддержать AiTerm',
        limitModalTitle: 'Лимит исчерпан',
        limitModalRequests: 'Вы превысили лимит запросов на перевод. Подождите обновления таймера.',
        limitModalDicts: 'Вы достигли лимита словарей.',
        limitModalWords: 'Вы достигли лимита сохраненных слов.',
        btnCloseModal: 'Закрыть',
        serverBusy: 'Серверы ИИ перегружены. Попробуйте через пару секунд.',
        networkError: 'Ошибка сети. Проверьте интернет.',
        genericError: 'Произошла ошибка. Попробуйте еще раз.',
        duplicateWarningText: 'Данное слово уже есть в словаре \'{dictName}\'. Вы точно хотите сохранить его?',
        btnYesAdd: 'Да, добавить',
        welcomeTitle: 'Добро пожаловать в AiTerm 1.0! 🎉',
        welcomeText1: 'Это полностью бесплатное расширение. Каждый день вам доступно по 30 запросов для главного и мини-окна.',
        welcomeText2: 'Проект развивается на энтузиазме. Если хотите, вы можете поддержать автора в настройках!',
        welcomeBtn: 'Погнали!',
        about_menu: 'О AiTerm',
        btnRenameDict: 'Переименовать словарь',
        sessionExpired: 'Сессия устарела. Войдите снова.',
        dictCreated: 'Словарь создан',
        failedToCreate: 'Не удалось создать',
        dictRenamed: 'Словарь переименоваван',
        failedToRename: 'Не удалось переименовать',
        nothingToSave: 'Нечего сохранять',
        savedSuccessfully: 'Успешно сохранено',
        failedToSave: 'Не удалось сохранить',
        profileDeleted: 'Профиль удален',
        failedToDeleteProfile: 'Не удалось удалить профиль',
        dictDeleted: 'Словарь удален',
        failedToDelete: 'Не удалось удалить',
        wordDeleted: 'Слово удалено',
        loginSuccessful: 'Успешный вход',
        serverError: 'Ошибка сервера',
        loginCancelled: 'Вход отменен',
        translateWordFirst: 'Сначала переведите слово',
        gibberishError: 'Не удалось распознать текст',
        notLoggedIn: 'Вы не вошли',
        logInBtn: 'Войти',
        settingsFeatures: 'Настройки и Функции',
        payCards: 'Оплата картами со всего мира: Visa, Mastercard, Apple Pay, Google Pay',
        quickTransPopup: 'Быстрый перевод (Pop-up)',
        quickTransDesc: 'Показывать плавающую кнопку AiTerm при выделении текста на любом сайте.',
        soonBadge: 'Больше крутих функций в будущих обновлениях! 🚀',
        aboutTitle1: 'Что такое AiTerm?',
        aboutText1: 'AiTerm — это продвинутый ИИ-переводчик, созданный для глубокого анализа контекста и изучения языков.',
        aboutTitle2: 'Почему именно AiTerm?',
        aboutText2: '• Контекстная точность: AiTerm анализирует весь текст, чтобы дать самый точный перевод.\n• Оценка CEFR: Моментально узнайте сложность слова.\n• Умные словари: Собирайте свою базу слов с полным контекстом и примерами.',
        aboutTitle3: 'Как пользоваться',
        aboutText3: '1. Перевод: Введите слово, выберите язык и нажмите "Перевести".\n2. Сохранение: Нажмите иконку "Сохранить", чтобы добавить слово в коллекцию.\n3. Управление: Организуйте свои словари в боковом меню.',
        devContacts: 'Связь с разработчиком',
        searchDict: 'Поиск словаря...',
        searchWord: 'Поиск слова...',
        noWordsSaved: 'Пока нет сохраненных слов.',
        nothingFound: 'Ничего не найдено.',
        confirmDeleteDict: 'Удалить этот словарь и все слова в нем навсегда?',
        confirmDeleteWord: 'Удалить это слово навсегда?',
        confirmDuplicateDict: 'Словарь с таким именем уже существует. Создать всё равно?',
        dictNamePlaceholder: 'Название словаря...',
        btnCreate: 'Создать',
        btnRename: 'Переименовать',
        newNamePlaceholder: 'Новое название...',
        emailCopied: 'Email скопирован',
        version: 'Версия 1.0'
    },
    es: {
        enterWord: 'Introduce palabra...',
        translation: 'Traducción...',
        cefrHint: 'Niveles oficiales de idiomas CEFR: de A1 (principiante) a C2 (fluido).',
        usageHint: 'Frecuencia de uso de la palabra en la vida diaria: de 1 (raro) a 10 (común).',
        examples: 'Ejemplos',
        synonyms: 'Sinónimos',
        explanation: 'Explicación',
        chooseLang: 'Elegir',
        examplesContent: 'Los ejemplos de la vida real aparecerán aquí para ayudarte a comprender el contexto.',
        synonymsContent: 'Aquí aparecerá una lista de sinónimos útiles para enriquecer tu vocabulario.',
        explanationContent: 'Las explicaciones detalladas y las reglas gramaticales se mostrarán aquí.',
        selectTargetWarning: 'Por favor, selecciona un idioma de traducción primero',
        sourceOptional: 'Auto',
        resetLanguage: 'Restablecer',
        loading: 'Traduciendo...',
        translateBtn: 'Traducir',
        save: 'Guardar',
        menuDictionaries: 'Diccionarios',
        menuPrices: 'Precios y Premium',
        menuChangeLang: 'Cambiar idioma',
        menuLogout: 'Cerrar sesión',
        menuRemoveProfile: 'Eliminar perfil',
        confirmTitle: '¿Estás seguro?',
        confirmLogoutText: 'Cerrarás la sesión de tu cuenta.',
        confirmRemoveText: 'Esta acción eliminará permanentemente tu perfil y todos los diccionarios.',
        btnCancel: 'Cancelar',
        btnConfirm: 'Sí',
        saveToDict: 'Guardar Palabra',
        noDicts: 'Aún no has creado ningún diccionario.',
        btnCreateDict: 'Crear diccionario',
        selectDict: 'Selecciona un diccionario o crea uno nuevo',
        authTitle: 'Bienvenido',
        authSubtitle: 'Inicia sesión para usar traducciones y diccionarios',
        authBtn: 'Iniciar sesión con Google',
        authLoading: 'Conectando...',
        planFree: 'Plan gratuito',
        month: 'mes',
        day: 'día',
        requests: 'Solicitudes de IA',
        currentPlan: 'Plan actual',
        upgradeBtn: 'Mejorar',
        hintAi: 'Dependiendo del modelo de IA que selecciones, recibirás respuestas de diferente calidad.',
        hintReq: 'El número de consultas afecta cuántas palabras puedes traducir por día.',
        textTooLong: 'Texto demasiado largo',
        fullTranslations: 'Traducciones completas',
        quickTranslations: 'Traducciones rápidas',
        resetAt: 'Se reinicia a las',
        limitReached: 'Límite alcanzado.',
        dictLimit: 'Límite de diccionarios alcanzado.',
        wordLimit: 'Límite de palabras guardadas alcanzado.',
        donateText: '¿Quieres ayudar a mejorar AiTerm? Puedes apoyar el proyecto con una donación. ¡No es obligatorio, pero siempre se agradece! ❤️',
        supportBtn: 'Apoyar AiTerm',
        limitModalTitle: 'Límite alcanzado',
        limitModalRequests: 'Has alcanzado tu límite de solicitudes de traducción. Espera a que se reinicie el temporizador.',
        limitModalDicts: 'Has alcanzado el número máximo de diccionarios.',
        limitModalWords: 'Has alcanzado el número máximo de palabras guardadas.',
        btnCloseModal: 'Cerrar',
        serverBusy: 'Los servidores de IA están sobrecargados. Inténtalo en unos segundos.',
        networkError: 'Error de red. Comprueba tu conexión.',
        genericError: 'Ocurrió un error. Inténtalo de nuevo.',
        duplicateWarningText: 'Esta palabra ya existe en el diccionario \'{dictName}\'. ¿Estás seguro de que quieres guardarla?',
        btnYesAdd: 'Sí, añadir',
        welcomeTitle: '¡Bienvenido a AiTerm 1.0! 🎉',
        welcomeText1: 'Esta es una extensión completamente gratuita. Tienes 30 solicitudes diarias para la ventana principal y 30 para la mini ventana.',
        welcomeText2: 'El proyecto se ha creado con pasión. Si te resulta útil, ¡puedes apoyar al autor en la configuración!',
        welcomeBtn: '¡Vamos!',
        about_menu: 'Sobre AiTerm',
        btnRenameDict: 'Renombrar diccionario',
        sessionExpired: 'Sesión expirada. Inicia sesión de nuevo.',
        dictCreated: 'Diccionario creado',
        failedToCreate: 'Error al crear',
        dictRenamed: 'Diccionario renombrado',
        failedToRename: 'Error al renombrar',
        nothingToSave: 'Nada que guardar',
        savedSuccessfully: 'Guardado con éxito',
        failedToSave: 'Error al guardar',
        profileDeleted: 'Perfil eliminado',
        failedToDeleteProfile: 'Error al eliminar el perfil',
        dictDeleted: 'Diccionario eliminado',
        failedToDelete: 'Error al eliminar',
        wordDeleted: 'Palabra eliminada',
        loginSuccessful: 'Inicio de sesión exitoso',
        serverError: 'Error del servidor',
        loginCancelled: 'Inicio de sesión cancelado',
        translateWordFirst: 'Traduce una palabra primero',
        gibberishError: 'No se pudo reconocer el texto',
        notLoggedIn: 'No has iniciado sesión',
        logInBtn: 'Iniciar sesión',
        settingsFeatures: 'Ajustes y Características',
        payCards: 'Paga con tarjetas desde cualquier parte del mundo: Visa, Mastercard, Apple Pay, Google Pay',
        quickTransPopup: 'Popup de traducción rápida',
        quickTransDesc: 'Mostrar un botón flotante de AiTerm al seleccionar texto en cualquier página.',
        soonBadge: '¡Más funciones emocionantes próximamente! 🚀',
        aboutTitle1: '¿Qué es AiTerm?',
        aboutText1: 'AiTerm es un asistente de traducción avanzado impulsado por IA, diseñado para el análisis contextual.',
        aboutTitle2: '¿Por qué elegir AiTerm?',
        aboutText2: '• Precisión contextual: Analiza el texto para dar el significado más relevante.\n• Evaluación CEFR: Identifica la dificultad de la palabra.\n• Diccionarios inteligentes: Guarda tus palabras con contexto.',
        aboutTitle3: 'Cómo usarlo',
        aboutText3: '1. Traducir: Escribe un término y haz clic en "Traducir".\n2. Guardar: Haz clic en el icono "Guardar".\n3. Administrar: Organiza tu vocabulario en el menú "Diccionarios".',
        devContacts: 'Contactos del desarrollador',
        searchDict: 'Buscar diccionario...',
        searchWord: 'Buscar palabra...',
        noWordsSaved: 'Aún no hay palabras guardadas.',
        nothingFound: 'No se encontró nada.',
        confirmDeleteDict: '¿Eliminar este diccionario y todas sus palabras permanentemente?',
        confirmDeleteWord: '¿Eliminar esta palabra permanentemente?',
        confirmDuplicateDict: 'Ya existe un diccionario con este nombre. ¿Crearlo de todos modos?',
        dictNamePlaceholder: 'Nombre del diccionario...',
        btnCreate: 'Crear',
        btnRename: 'Renommar',
        newNamePlaceholder: 'Nuevo nombre...',
        emailCopied: 'Correo electrónico copiado',
        version: 'Versión 1.0'
    },
    uk: {
        enterWord: 'Введіть слово...',
        translation: 'Переклад...',
        cefrHint: 'Офіційна шкала рівнів CEFR: від A1 (початківець) до C2 (професіонал).',
        usageHint: 'Частота використання слова у мові: від 1 (рідко) до 10 (дуже часто).',
        examples: 'Приклади',
        synonyms: 'Синоніми',
        explanation: 'Пояснення',
        chooseLang: 'Обрати',
        examplesContent: 'Тут будуть наведені реальні приклади з життя для кращого розуміння контексту.',
        synonymsContent: 'Тут з\'явиться список корисних синонімів, які допоможуть збагатити словниковий запас.',
        explanationContent: 'Тут буде детальне пояснення значення слова, його походження та правила використання.',
        selectTargetWarning: 'Будь ласка, спочатку оберіть мову перекладу',
        sourceOptional: 'Авто',
        resetLanguage: 'Скинути',
        loading: 'Перекладаю...',
        translateBtn: 'Перекласти',
        save: 'Зберегти',
        menuDictionaries: 'Словники',
        menuPrices: 'Ціни та Premium',
        menuChangeLang: 'Змінити мову',
        menuLogout: 'Вийти',
        menuRemoveProfile: 'Видалити профіль',
        confirmTitle: 'Ви впевнені?',
        confirmLogoutText: 'Ви вийдете зі свого облікового запису.',
        confirmRemoveText: 'Ця дія назавжди видалить ваш профіль та усі словники.',
        btnCancel: 'Скасувати',
        btnConfirm: 'Так',
        saveToDict: 'Зберегти слово',
        noDicts: 'Ви ще не створили жодного словника.',
        btnCreateDict: 'Створити словник',
        selectDict: 'Оберіть словник або створіть новий',
        authTitle: 'Ласкаво просимо',
        authSubtitle: 'Увійдіть, щоб використовувати переклади та словники',
        authBtn: 'Увійти через Google',
        authLoading: 'Підключення...',
        planFree: 'Безкоштовний план',
        month: 'місяць',
        day: 'день',
        requests: 'AI запити',
        currentPlan: 'Поточний план',
        upgradeBtn: 'Покращити',
        hintAi: 'Обрана ШІ-модель впливає на якість та глибину отримуваного перекладу.',
        hintReq: 'Кількість запитів визначає, скільки слів ви можете перекласти за день.',
        textTooLong: 'Занадто довгий текст',
        fullTranslations: 'Повні переклади',
        quickTranslations: 'Швидкі переклади',
        resetAt: 'Оновлення о',
        limitReached: 'Ліміт вичерпано. Дочекайтесь оновлення.',
        dictLimit: 'Ліміт словників вичерпано.',
        wordLimit: 'Ліміт збережених слів вичерпано.',
        donateText: 'Хочеш допомогти AiTerm стати ще краще? Ти можеш підтримати проект донатом. Це не обов\'язково, але завжди дуже цінується! ❤️',
        supportBtn: 'Підтримати AiTerm',
        limitModalTitle: 'Ліміт вичерпано',
        limitModalRequests: 'Ви перевищили ліміт запитів на переклад. Зачекайте на оновлення таймера.',
        limitModalDicts: 'Ви досягли ліміту словників.',
        limitModalWords: 'Ви досягли ліміту збережених слів.',
        btnCloseModal: 'Закрити',
        serverBusy: 'Сервери ШІ перевантажені. Спробуйте через кілька секунд.',
        networkError: 'Помилка мережі. Перевірте з\'єднання.',
        genericError: 'Сталася помилка. Спробуйте ще раз.',
        duplicateWarningText: 'Це слово вже є у словнику \'{dictName}\'. Ви точно хочете зберегти його?',
        btnYesAdd: 'Так, додати',
        welcomeTitle: 'Ласкаво просимо до AiTerm 1.0! 🎉',
        welcomeText1: 'Це повністю безкоштовне розширення. Кожного дня вам доступно по 30 запитів для головного та міні-вікна.',
        welcomeText2: 'Проєкт розвивається на ентузіазмі. Якщо бажаєте, ви можете підтримати автора в налаштуваннях!',
        welcomeBtn: 'Поїхали!',
        about_menu: 'Про AiTerm',
        btnRenameDict: 'Перейменувати словник',
        sessionExpired: 'Сесія застаріла. Увійдіть знову.',
        dictCreated: 'Словник створено',
        failedToCreate: 'Не вдалося створити',
        dictRenamed: 'Словник перейменовано',
        failedToRename: 'Не вдалося перейменувати',
        nothingToSave: 'Нічого зберігати',
        savedSuccessfully: 'Успішно збережено',
        failedToSave: 'Не вдалося зберегти',
        profileDeleted: 'Профіль видалено',
        failedToDeleteProfile: 'Не вдалося видалити профіль',
        dictDeleted: 'Словник видалено',
        failedToDelete: 'Не вдалося видалити',
        wordDeleted: 'Слово видалено',
        loginSuccessful: 'Успішний вхід',
        serverError: 'Помилка сервера',
        loginCancelled: 'Вхід скасовано',
        translateWordFirst: 'Спочатку перекладіть слово',
        gibberishError: 'Не вдалося розпізнати текст',
        notLoggedIn: 'Ви не увійшли',
        logInBtn: 'Увійти',
        settingsFeatures: 'Налаштування та Функції',
        payCards: 'Оплата картками з усього світу: Visa, Mastercard, Apple Pay, Google Pay',
        quickTransPopup: 'Швидкий переклад (Pop-up)',
        quickTransDesc: 'Показувати плаваючу кнопку AiTerm під час виділення тексту на будь-якому сайті.',
        soonBadge: 'Більше крутих функцій у майбутніх оновленнях! 🚀',
        aboutTitle1: 'Що таке AiTerm?',
        aboutText1: 'AiTerm — це просунутий ШІ-перекладач, створений для глибокого аналізу контексту та вивчення мов.',
        aboutTitle2: 'Чому саме AiTerm?',
        aboutText2: '• Контекстна точність: AiTerm аналізує весь текст, щоб дати найточніший переклад.\n• Оцінка CEFR: Миттєво дізнайтеся складність слова.\n• Розумні словники: Збирайте свою базу слів із повним контекстом та прикладами.',
        aboutTitle3: 'Як користуватися',
        aboutText3: '1. Переклад: Введіть слово, оберіть мову та натисніть "Перекласти".\n2. Збереження: Натисніть іконку "Зберегти", щоб додати слово до колекції.\n3. Керування: Організуйте свої словники у бічному меню.',
        devContacts: 'Зв\'язок з розробником',
        searchDict: 'Пошук словника...',
        searchWord: 'Пошук слова...',
        noWordsSaved: 'Поки немає збережених слів.',
        nothingFound: 'Нічого не знайдено.',
        confirmDeleteDict: 'Видалити цей словник та всі слова в ньому назавжди?',
        confirmDeleteWord: 'Видалити це слово назавжди?',
        confirmDuplicateDict: 'Словник з таким ім\'ям вже існує. Створити все одно?',
        dictNamePlaceholder: 'Назва словника...',
        btnCreate: 'Створити',
        btnRename: 'Перейменувати',
        newNamePlaceholder: 'Нова назва...',
        emailCopied: 'Email скопійовано',
        version: 'Версія 1.0'
    }
};

export const availableLanguages = [
    {code: 'ar', name: 'Arabic', flag: 'sa', supportsUI: true},
    {code: 'bn', name: 'Bengali', flag: 'bd', supportsUI: false},
    {code: 'zh', name: 'Chinese', flag: 'cn', supportsUI: true},
    {code: 'cs', name: 'Czech', flag: 'cz', supportsUI: false},
    {code: 'da', name: 'Danish', flag: 'dk', supportsUI: false},
    {code: 'nl', name: 'Dutch', flag: 'nl', supportsUI: false},
    {code: 'en', name: 'English', flag: 'gb', supportsUI: true},
    {code: 'fi', name: 'Finnish', flag: 'fi', supportsUI: false},
    {code: 'fr', name: 'French', flag: 'fr', supportsUI: true},
    {code: 'de', name: 'German', flag: 'de', supportsUI: false},
    {code: 'el', name: 'Greek', flag: 'gr', supportsUI: false},
    {code: 'he', name: 'Hebrew', flag: 'il', supportsUI: false},
    {code: 'hi', name: 'Hindi', flag: 'in', supportsUI: true},
    {code: 'hu', name: 'Hungarian', flag: 'hu', supportsUI: false},
    {code: 'id', name: 'Indonesian', flag: 'id', supportsUI: false},
    {code: 'it', name: 'Italian', flag: 'it', supportsUI: false},
    {code: 'ja', name: 'Japanese', flag: 'jp', supportsUI: false},
    {code: 'ko', name: 'Korean', flag: 'kr', supportsUI: false},
    {code: 'no', name: 'Norwegian', flag: 'no', supportsUI: false},
    {code: 'fa', name: 'Persian', flag: 'ir', supportsUI: false},
    {code: 'pl', name: 'Polish', flag: 'pl', supportsUI: true},
    {code: 'pt', name: 'Portuguese', flag: 'pt', supportsUI: true},
    {code: 'ro', name: 'Romanian', flag: 'ro', supportsUI: false},
    {code: 'ru', name: 'Russian', flag: 'ru', supportsUI: true},
    {code: 'es', name: 'Spanish', flag: 'es', supportsUI: true},
    {code: 'sv', name: 'Swedish', flag: 'se', supportsUI: false},
    {code: 'th', name: 'Thai', flag: 'th', supportsUI: false},
    {code: 'tr', name: 'Turkish', flag: 'tr', supportsUI: false},
    {code: 'uk', name: 'Ukrainian', flag: 'ua', supportsUI: true},
    {code: 'vi', name: 'Vietnamese', flag: 'vn', supportsUI: false}
];

export const detectLanguage = (text: string): string | null => {
    if (!text.trim()) return null;
    if (/[\u3040-\u30FF\u4E00-\u9FFF]/.test(text) && /[\u3040-\u30FF]/.test(text)) return 'ja';
    if (/[\uAC00-\uD7AF]/.test(text)) return 'ko';
    if (/[\u4E00-\u9FFF]/.test(text)) return 'zh';
    if (/[\u0600-\u06FF]/.test(text)) return 'ar';
    if (/[\u0900-\u097F]/.test(text)) return 'hi';
    if (/[\u0E00-\u0E7F]/.test(text)) return 'th';
    if (/[\u0590-\u05FF]/.test(text)) return 'he';
    if (/[ыэъё]/i.test(text)) return 'ru';
    if (/[ієїґ]/i.test(text)) return 'uk';
    if (/[а-я]/i.test(text)) return 'ru';
    if (/[ñ¿¡]/i.test(text)) return 'es';
    if (/[łśćżźąę]/i.test(text)) return 'pl';
    if (/[ãõ]/i.test(text)) return 'pt';
    if (/[öäüß]/i.test(text)) return 'de';
    if (/[æøå]/i.test(text)) return 'da';
    return null;
};