// --- Helper для автоматического перевода названий языков ---
export const getLanguageName = (langCode: string, uiLang: string): string => {
    try {
        const displayNames = new Intl.DisplayNames([uiLang], {type: 'language'});
        const name = displayNames.of(langCode);
        if (name) {
            return name.charAt(0).toUpperCase() + name.slice(1);
        }
    } catch (e) {
        console.error("Language translation error", e);
    }
    return availableLanguages.find(l => l.code === langCode)?.name || langCode;
};

// --- Translation Dictionary ---
export const translations = {
    ar: {
        enterWord: 'أدخل الكلمة...',
        translation: 'الترجمة...',
        cefrHint: 'مستويات CEFR الرسمية: من A1 (مبتدئ) إلى C2 (متقدم).',
        usageHint: 'وتيرة الاستخدام في الحياة اليومية: من 1 (نادر) إلى 10 (شائع).',
        examples: 'أمثلة',
        synonyms: 'مرادفات',
        explanation: 'تفسير',
        chooseLang: 'اختر',
        examplesContent: 'ستظهر هنا أمثلة من الحياة الواقعية لمساعدتك على فهم السياق.',
        synonymsContent: 'ستظهر هنا قائمة بالمرادفات المفيدة لإثراء مفرداتك.',
        explanationContent: 'ستظهر هنا التفسيرات التفصيلية والأصول والقواعد النحوية.',
        selectTargetWarning: 'يرجى تحديد لغة الترجمة أولاً',
        sourceOptional: 'تلقائي',
        resetLanguage: 'إعادة تعيين',
        loading: 'جارٍ الترجمة...',
        translateBtn: 'ترجمة',
        save: 'حفظ',
        menuDictionaries: 'قواميس',
        menuPrices: 'الأسعار والمميزات',
        menuChangeLang: 'تغيير اللغة',
        menuLogout: 'تسجيل الخروج',
        menuRemoveProfile: 'حذف الحساب',
        confirmTitle: 'هل أنت متأكد؟',
        confirmLogoutText: 'سيتم تسجيل خروجك من الحساب.',
        confirmRemoveText: 'هذا الإجراء سيحذف حسابك وبياناتك نهائياً.',
        btnCancel: 'إلغاء',
        btnConfirm: 'نعم',
        saveToDict: 'حفظ الكلمة',
        noDicts: 'لم تقم بإنشاء أي قواميس حتى الآن.',
        btnCreateDict: 'إنشاء قاموس',
        selectDict: 'اختر قاموسًا أو أنشئ واحدًا جديدًا',
        authTitle: 'مرحباً',
        authSubtitle: 'قم بتسجيل الدخول لاستخدام الترجمات والقواميس',
        authBtn: 'تسجيل الدخول باستخدام Google',
        authLoading: 'جاري الاتصال...',
        planFree: 'Free plan',
        month: 'month',
        day: 'day',
        requests: 'Requests',
        currentPlan: 'Current plan',
        upgradeBtn: 'Upgrade',
        hintAi: 'Depending on the AI model you select, you will receive answers of different quality and depth.',
        hintReq: 'The number of queries affects how many words you can translate per day.'
    },
    zh: {
        enterWord: '输入单词...',
        translation: '翻译...',
        cefrHint: '官方 CEFR 语言级别：从 A1（初学者）到 C2（精通）。',
        usageHint: '日常生活中单词的使用频率：从 1（罕见）到 10（常见）。',
        examples: '例句',
        synonyms: '同义词',
        explanation: '解释',
        chooseLang: '选择',
        examplesContent: '现实生活中的例句将显示在这里，帮助您理解上下文。',
        synonymsContent: '这里将显示有用的同义词列表，以丰富您的词汇量。',
        explanationContent: '该单词的详细解释、起源和语法规则将显示在此处。',
        selectTargetWarning: '请先选择翻译语言',
        sourceOptional: '自动',
        resetLanguage: '重置',
        loading: '翻译中...',
        translateBtn: '翻译',
        save: '保存',
        menuDictionaries: '词典',
        menuPrices: '价格与高级版',
        menuChangeLang: '更改语言',
        menuLogout: '登出',
        menuRemoveProfile: '删除资料',
        confirmTitle: '你确定吗？',
        confirmLogoutText: '您将从您的账户中注销。',
        confirmRemoveText: '此操作将永久删除您的账户和数据。',
        btnCancel: '取消',
        btnConfirm: '是的',
        saveToDict: '保存单词',
        noDicts: '您还没有创建任何字典。',
        btnCreateDict: '创建字典',
        selectDict: '选择字典或创建新字典',
        authTitle: '欢迎',
        authSubtitle: '登录以使用翻译和词典',
        authBtn: '使用 Google 登录',
        authLoading: '连接中...',
        planFree: 'Free plan',
        month: 'month',
        day: 'day',
        requests: 'Requests',
        currentPlan: 'Current plan',
        upgradeBtn: 'Upgrade',
        hintAi: 'Depending on the AI model you select, you will receive answers of different quality and depth.',
        hintReq: 'The number of queries affects how many words you can translate per day.'
    },
    en: {
        enterWord: 'Enter word...',
        translation: 'Translation...',
        cefrHint: 'Official CEFR language levels: from A1 (beginner) to C2 (fluent).',
        usageHint: 'Frequency of word usage in daily life: from 1 (rare) to 10 (common).',
        examples: 'Examples',
        synonyms: 'Synonyms',
        explanation: 'Explanation',
        chooseLang: 'Select',
        examplesContent: 'Real-life examples will appear here to help you understand the context.',
        synonymsContent: 'A list of useful synonyms will appear here to enrich your vocabulary.',
        explanationContent: 'Detailed explanations, origins, and grammar rules for this word will be shown here.',
        selectTargetWarning: 'Please select a translation language first',
        sourceOptional: 'Auto',
        resetLanguage: 'Reset',
        loading: 'Translating...',
        translateBtn: 'Translate',
        save: 'Save',
        menuDictionaries: 'Dictionaries',
        menuPrices: 'Prices & Premium',
        menuChangeLang: 'Change Language',
        menuLogout: 'Log out',
        menuRemoveProfile: 'Remove profile',
        confirmTitle: 'Are you sure?',
        confirmLogoutText: 'You will be logged out of your account.',
        confirmRemoveText: 'This action will permanently delete your account and data.',
        btnCancel: 'Cancel',
        btnConfirm: 'Yes, do it',
        saveToDict: 'Save Word',
        noDicts: 'You haven\'t created any dictionaries yet.',
        btnCreateDict: 'Create dictionary',
        selectDict: 'Select a dictionary or create a new one',
        authTitle: 'Welcome',
        authSubtitle: 'Sign in to use translations and dictionaries',
        authBtn: 'Sign in with Google',
        authLoading: 'Connecting...',
        planFree: 'Free plan',
        month: 'month',
        day: 'day',
        requests: 'AI requests',
        currentPlan: 'Current plan',
        upgradeBtn: 'Upgrade',
        hintAi: 'Depending on the AI model you select, you will receive answers of different quality and depth.',
        hintReq: 'The number of queries affects how many words you can translate per day.'
    },
    fr: {
        enterWord: 'Entrez un mot...',
        translation: 'Traduction...',
        cefrHint: 'Niveaux de langue officiels du CECRL : de A1 (débutant) à C2 (bilingue).',
        usageHint: 'Fréquence d\'utilisation du mot au quotidien : de 1 (rare) à 10 (courant).',
        examples: 'Exemples',
        synonyms: 'Synonymes',
        explanation: 'Explication',
        chooseLang: 'Choisir',
        examplesContent: 'Des exemples de la vie réelle apparaîtront ici pour vous aider à comprendre le contexte.',
        synonymsContent: 'Une liste de synonymes utiles apparaîtra ici pour enrichir votre vocabulaire.',
        explanationContent: 'Des explications détaillées, les origines et les règles de grammaire seront affichées ici.',
        selectTargetWarning: 'Veuillez d\'abord choisir une langue de traduction',
        sourceOptional: 'Auto',
        resetLanguage: 'Réinitialiser',
        loading: 'Traduction...',
        translateBtn: 'Traduire',
        save: 'Sauver',
        menuDictionaries: 'Dictionnaires',
        menuPrices: 'Prix & Premium',
        menuChangeLang: 'Changer de langue',
        menuLogout: 'Se déconnecter',
        menuRemoveProfile: 'Supprimer le profil',
        confirmTitle: 'Êtes-vous sûr ?',
        confirmLogoutText: 'Vous serez déconnecté de votre compte.',
        confirmRemoveText: 'Cette action supprimera définitivement votre compte et vos données.',
        btnCancel: 'Annuler',
        btnConfirm: 'Oui',
        saveToDict: 'Enregistrer le mot',
        noDicts: 'Vous n\'avez pas encore créé de dictionnaire.',
        btnCreateDict: 'Créer un dictionnaire',
        selectDict: 'Sélectionnez un dictionnaire ou créez-en un',
        authTitle: 'Bienvenue',
        authSubtitle: 'Connectez-vous pour utiliser les traductions et les dictionnaires',
        authBtn: 'Se connecter avec Google',
        authLoading: 'Connexion...',
        planFree: 'Free plan',
        month: 'month',
        day: 'day',
        requests: 'Requests',
        currentPlan: 'Current plan',
        upgradeBtn: 'Upgrade',
        hintAi: 'Depending on the AI model you select, you will receive answers of different quality and depth.',
        hintReq: 'The number of queries affects how many words you can translate per day.'
    },
    hi: {
        enterWord: 'शब्द दर्ज करें...',
        translation: 'अनुवाद...',
        cefrHint: 'आधिकारिक CEFR भाषा स्तर: A1 (शुरुआती) से C2 (प्रवाहपूर्ण) तक।',
        usageHint: 'दैनिक जीवन में शब्द के उपयोग की आवृत्ति: 1 (दुर्लभ) से 10 (सामान्य) तक।',
        examples: 'उदाहरण',
        synonyms: 'पर्यायवाची',
        explanation: 'व्याख्या',
        chooseLang: 'चुनें',
        examplesContent: 'संदर्भ को पूरी तरह से समझने में आपकी मदद करने के लिए वास्तविक जीवन के उदाहरण यहां दिखाई देंगे।',
        synonymsContent: 'आपकी दैनिक शब्दावली को समृद्ध करने के लिए उपयोगी पर्यायवाची शब्दों की सूची यहां दिखाई देगी।',
        explanationContent: 'इस शब्द के लिए विस्तृत स्पष्टीकरण, उत्पत्ति और व्याकरण के नियम यहां दिखाए जाएंगे।',
        selectTargetWarning: 'कृपया पहले अनुवाद की भाषा चुनें',
        sourceOptional: 'स्वत:',
        resetLanguage: 'रीसेट',
        loading: 'अनुवाद...',
        translateBtn: 'अनुवाद',
        save: 'सहेजें',
        menuDictionaries: 'शब्दकोश',
        menuPrices: 'कीमतें और प्रीमियम',
        menuChangeLang: 'भाषा बदलें',
        menuLogout: 'लॉग आउट',
        menuRemoveProfile: 'प्रोफ़ाइल हटाएं',
        confirmTitle: 'क्या आप सुनिश्चित हैं?',
        confirmLogoutText: 'आप अपने खाते से लॉग आउट हो जाएंगे।',
        confirmRemoveText: 'यह क्रिया आपके खाते और डेटा को स्थायी रूप से हटा देगी।',
        btnCancel: 'रद्द करें',
        btnConfirm: 'हां',
        saveToDict: 'शब्द सहेजें',
        noDicts: 'आपने अभी तक कोई शब्दकोश नहीं बनाया है।',
        btnCreateDict: 'शब्दकोश बनाएं',
        selectDict: 'शब्दकोश चुनें या नया बनाएं',
        authTitle: 'स्वागत है',
        authSubtitle: 'अनुवाद और शब्दकोशों का उपयोग करने के लिए साइन इन करें',
        authBtn: 'Google के साथ साइन इन करें',
        authLoading: 'कनेक्ट हो रहा है...',
        planFree: 'Free plan',
        month: 'month',
        day: 'day',
        requests: 'Requests',
        currentPlan: 'Current plan',
        upgradeBtn: 'Upgrade',
        hintAi: 'Depending on the AI model you select, you will receive answers of different quality and depth.',
        hintReq: 'The number of queries affects how many words you can translate per day.'
    },
    pl: {
        enterWord: 'Wpisz słowo...',
        translation: 'Tłumaczenie...',
        cefrHint: 'Oficjalne poziomy biegłości językowej CEFR: od A1 (początkujący) do C2 (biegły).',
        usageHint: 'Częstotliwość użycia słowa w życiu codziennym: od 1 (rzadko) do 10 (często).',
        examples: 'Przykłady',
        synonyms: 'Synonimy',
        explanation: 'Wyjaśnienie',
        chooseLang: 'Wybierz',
        examplesContent: 'Pojawią się tu przykłady z życia wzięte, aby pomóc ci zrozumieć kontekst.',
        synonymsContent: 'Tutaj pojawi się lista przydatnych synonimów, które wzbogacą twoje słownictwo.',
        explanationContent: 'Tutaj wyświetlone zostaną szczegółowe wyjaśnienia i zasady gramatyczne dla tego słowa.',
        selectTargetWarning: 'Proszę najpierw wybrać język tłumaczenia',
        sourceOptional: 'Auto',
        resetLanguage: 'Resetuj',
        loading: 'Tłumaczenie...',
        translateBtn: 'Tłumacz',
        save: 'Zapisz',
        menuDictionaries: 'Słowniki',
        menuPrices: 'Ceny i Premium',
        menuChangeLang: 'Zmień język',
        menuLogout: 'Wyloguj',
        menuRemoveProfile: 'Usuń profil',
        confirmTitle: 'Jesteś pewien?',
        confirmLogoutText: 'Zostaniesz wylogowany ze swojego konta.',
        confirmRemoveText: 'Ta akcja trwale usunie twoje konto i dane.',
        btnCancel: 'Anuluj',
        btnConfirm: 'Tak',
        saveToDict: 'Zapisz słowo',
        noDicts: 'Nie utworzyłeś jeszcze żadnych słowników.',
        btnCreateDict: 'Utwórz słownik',
        selectDict: 'Wybierz słownik lub utwórz nowy',
        authTitle: 'Witamy',
        authSubtitle: 'Zaloguj się, aby korzystać z tłumaczeń i słowników',
        authBtn: 'Zaloguj się przez Google',
        authLoading: 'Łączenie...',
        planFree: 'Free plan',
        month: 'month',
        day: 'day',
        requests: 'Requests',
        currentPlan: 'Current plan',
        upgradeBtn: 'Upgrade',
        hintAi: 'Depending on the AI model you select, you will receive answers of different quality and depth.',
        hintReq: 'The number of queries affects how many words you can translate per day.'
    },
    pt: {
        enterWord: 'Digite a palavra...',
        translation: 'Tradução...',
        cefrHint: 'Níveis oficiais de idiomas do CEFR: de A1 (iniciante) a C2 (fluente).',
        usageHint: 'Frequência de uso da palavra no dia a dia: de 1 (raro) a 10 (comum).',
        examples: 'Exemplos',
        synonyms: 'Sinônimos',
        explanation: 'Explicação',
        chooseLang: 'Escolher',
        examplesContent: 'Exemplos da vida real aparecerão aqui para ajudar você a entender o contexto.',
        synonymsContent: 'Uma lista de sinônimos úteis aparecerá aqui para enriquecer seu vocabulário.',
        explanationContent: 'Explicações detalhadas, origens e regras gramaticais para esta palavra serão mostradas aqui.',
        selectTargetWarning: 'Por favor, selecione um idioma de tradução primeiro',
        sourceOptional: 'Auto',
        resetLanguage: 'Redefinir',
        loading: 'Traduzindo...',
        translateBtn: 'Traduzir',
        save: 'Salvar',
        menuDictionaries: 'Dicionários',
        menuPrices: 'Preços e Premium',
        menuChangeLang: 'Mudar idioma',
        menuLogout: 'Sair',
        menuRemoveProfile: 'Remover perfil',
        confirmTitle: 'Tem certeza?',
        confirmLogoutText: 'Você será desconectado da sua conta.',
        confirmRemoveText: 'Esta ação excluirá permanentemente sua conta e dados.',
        btnCancel: 'Cancelar',
        btnConfirm: 'Sim',
        saveToDict: 'Salvar Palavra',
        noDicts: 'Você ainda não criou nenhum dicionário.',
        btnCreateDict: 'Criar dicionário',
        selectDict: 'Selecione um dicionário ou crie um novo',
        authTitle: 'Bem-vindo',
        authSubtitle: 'Faça login para usar traduções e dicionários',
        authBtn: 'Fazer login com o Google',
        authLoading: 'Conectando...',
        planFree: 'Free plan',
        month: 'month',
        day: 'day',
        requests: 'Requests',
        currentPlan: 'Current plan',
        upgradeBtn: 'Upgrade',
        hintAi: 'Depending on the AI model you select, you will receive answers of different quality and depth.',
        hintReq: 'The number of queries affects how many words you can translate per day.'
    },
    ru: {
        enterWord: 'Введите слово...',
        translation: 'Перевод...',
        cefrHint: 'Официальная шкала уровней CEFR: от A1 (начинающий) до C2 (продвинутый).',
        usageHint: 'Частота использования слова в повседневной речи: от 1 (редко) до 10 (часто).',
        examples: 'Примеры',
        synonyms: 'Синонимы',
        explanation: 'Объяснение',
        chooseLang: 'Выбрать',
        examplesContent: 'Здесь появятся реальные примеры из жизни для понимания контекста.',
        synonymsContent: 'Здесь появится список полезных синонимов для обогащения словарного запаса.',
        explanationContent: 'Здесь будут показаны подробные объяснения и грамматические правила.',
        selectTargetWarning: 'Сначала выберите язык перевода',
        sourceOptional: 'Авто',
        resetLanguage: 'Сбросить',
        loading: 'Перевожу...',
        translateBtn: 'Перевести',
        save: 'Сохранить',
        menuDictionaries: 'Словари',
        menuPrices: 'Цены и Premium',
        menuChangeLang: 'Сменить язык',
        menuLogout: 'Выйти',
        menuRemoveProfile: 'Удалить профиль',
        confirmTitle: 'Вы уверены?',
        confirmLogoutText: 'Вы выйдете из своего аккаунта.',
        confirmRemoveText: 'Это действие навсегда удалит ваш аккаунт и данные.',
        btnCancel: 'Отмена',
        btnConfirm: 'Да',
        saveToDict: 'Сохранить слово',
        noDicts: 'Вы еще не создали ни одного словаря.',
        btnCreateDict: 'Создать словарь',
        selectDict: 'Выберите словарь или создайте новый',
        authTitle: 'Добро пожаловать',
        authSubtitle: 'Войдите, чтобы использовать переводы и словари',
        authBtn: 'Войти через Google',
        authLoading: 'Подключение...',
        planFree: 'Бесплатный план',
        month: 'месяц',
        day: 'день',
        requests: 'AI запросы',
        currentPlan: 'Текущий план',
        upgradeBtn: 'Улучшить',
        hintAi: 'Выбранная ИИ-модель влияет на качество и глубину получаемого перевода.',
        hintReq: 'Количество запросов определяет, сколько слов вы можете перевести за день.'
    },
    es: {
        enterWord: 'Introduce palabra...',
        translation: 'Traducción...',
        cefrHint: 'Niveles oficiales de idiomas CEFR: de A1 (principiante) a C2 (fluido).',
        usageHint: 'Frecuencia de uso de la palabra en la vida diaria: de 1 (raro) a 10 (común).',
        examples: 'Ejemplos',
        synonyms: 'Sinónimos',
        explanation: 'Explicación',
        chooseLang: 'Elegir',
        examplesContent: 'Los ejemplos de la vida real aparecerán aquí para ayudarte a comprender el contexto.',
        synonymsContent: 'Aquí aparecerá una lista de sinónimos útiles para enriquecer tu vocabulario.',
        explanationContent: 'Las explicaciones detalladas y las reglas gramaticales se mostrarán aquí.',
        selectTargetWarning: 'Por favor, selecciona un idioma de traducción primero',
        sourceOptional: 'Auto',
        resetLanguage: 'Restablecer',
        loading: 'Traduciendo...',
        translateBtn: 'Traducir',
        save: 'Guardar',
        menuDictionaries: 'Diccionarios',
        menuPrices: 'Precios y Premium',
        menuChangeLang: 'Cambiar idioma',
        menuLogout: 'Cerrar sesión',
        menuRemoveProfile: 'Eliminar perfil',
        confirmTitle: '¿Estás seguro?',
        confirmLogoutText: 'Cerrarás la sesión de tu cuenta.',
        confirmRemoveText: 'Esta acción eliminará permanentemente tu cuenta y datos.',
        btnCancel: 'Cancelar',
        btnConfirm: 'Sí',
        saveToDict: 'Guardar Palabra',
        noDicts: 'Aún no has creado ningún diccionario.',
        btnCreateDict: 'Crear diccionario',
        selectDict: 'Selecciona un diccionario o crea uno nuevo',
        authTitle: 'Bienvenido',
        authSubtitle: 'Inicia sesión para usar traducciones y diccionarios',
        authBtn: 'Iniciar sesión con Google',
        authLoading: 'Conectando...',
        planFree: 'Free plan',
        month: 'month',
        day: 'day',
        requests: 'Requests',
        currentPlan: 'Current plan',
        upgradeBtn: 'Upgrade',
        hintAi: 'Depending on the AI model you select, you will receive answers of different quality and depth.',
        hintReq: 'The number of queries affects how many words you can translate per day.'
    },
    uk: {
        enterWord: 'Введіть слово...',
        translation: 'Переклад...',
        cefrHint: 'Офіційна шкала рівнів CEFR: від A1 (початківець) до C2 (професіонал).',
        usageHint: 'Частота використання слова у мові: від 1 (рідко) до 10 (дуже часто).',
        examples: 'Приклади',
        synonyms: 'Синоніми',
        explanation: 'Пояснення',
        chooseLang: 'Обрати',
        examplesContent: 'Тут будуть наведені реальні приклади з життя для кращого розуміння контексту.',
        synonymsContent: 'Тут з\'явиться список корисних синонімів, які допоможуть збагатити словниковий запас.',
        explanationContent: 'Тут буде детальне пояснення значення слова, його походження та правила використання.',
        selectTargetWarning: 'Будь ласка, спочатку оберіть мову перекладу',
        sourceOptional: 'Авто',
        resetLanguage: 'Скинути',
        loading: 'Перекладаю...',
        translateBtn: 'Перекласти',
        save: 'Зберегти',
        menuDictionaries: 'Словники',
        menuPrices: 'Ціни та Premium',
        menuChangeLang: 'Змінити мову',
        menuLogout: 'Вийти',
        menuRemoveProfile: 'Видалити профіль',
        confirmTitle: 'Ви впевнені?',
        confirmLogoutText: 'Ви вийдете зі свого облікового запису.',
        confirmRemoveText: 'Ця дія назавжди видалить ваш профіль та всі дані.',
        btnCancel: 'Скасувати',
        btnConfirm: 'Так',
        saveToDict: 'Зберегти слово',
        noDicts: 'Ви ще не створили жодного словника.',
        btnCreateDict: 'Створити словник',
        selectDict: 'Оберіть словник або створіть новий',
        authTitle: 'Ласкаво просимо',
        authSubtitle: 'Увійдіть, щоб використовувати переклади та словники',
        authBtn: 'Увійти через Google',
        authLoading: 'Підключення...',
        planFree: 'Безкоштовний план',
        month: 'місяць',
        day: 'день',
        requests: 'AI запити',
        currentPlan: 'Поточний план',
        upgradeBtn: 'Покращити',
        hintAi: 'Обрана ШІ-модель впливає на якість та глибину отримуваного перекладу.',
        hintReq: 'Кількість запитів визначає, скільки слів ви можете перекласти за день.'
    }
};

export const availableLanguages = [
    {code: 'ar', name: 'Arabic', flag: 'sa', supportsUI: true},
    {code: 'bn', name: 'Bengali', flag: 'bd', supportsUI: false},
    {code: 'zh', name: 'Chinese', flag: 'cn', supportsUI: true},
    {code: 'cs', name: 'Czech', flag: 'cz', supportsUI: false},
    {code: 'da', name: 'Danish', flag: 'dk', supportsUI: false},
    {code: 'nl', name: 'Dutch', flag: 'nl', supportsUI: false},
    {code: 'en', name: 'English', flag: 'gb', supportsUI: true},
    {code: 'fi', name: 'Finnish', flag: 'fi', supportsUI: false},
    {code: 'fr', name: 'French', flag: 'fr', supportsUI: true},
    {code: 'de', name: 'German', flag: 'de', supportsUI: false},
    {code: 'el', name: 'Greek', flag: 'gr', supportsUI: false},
    {code: 'he', name: 'Hebrew', flag: 'il', supportsUI: false},
    {code: 'hi', name: 'Hindi', flag: 'in', supportsUI: true},
    {code: 'hu', name: 'Hungarian', flag: 'hu', supportsUI: false},
    {code: 'id', name: 'Indonesian', flag: 'id', supportsUI: false},
    {code: 'it', name: 'Italian', flag: 'it', supportsUI: false},
    {code: 'ja', name: 'Japanese', flag: 'jp', supportsUI: false},
    {code: 'ko', name: 'Korean', flag: 'kr', supportsUI: false},
    {code: 'no', name: 'Norwegian', flag: 'no', supportsUI: false},
    {code: 'fa', name: 'Persian', flag: 'ir', supportsUI: false},
    {code: 'pl', name: 'Polish', flag: 'pl', supportsUI: true},
    {code: 'pt', name: 'Portuguese', flag: 'pt', supportsUI: true},
    {code: 'ro', name: 'Romanian', flag: 'ro', supportsUI: false},
    {code: 'ru', name: 'Russian', flag: 'ru', supportsUI: true},
    {code: 'es', name: 'Spanish', flag: 'es', supportsUI: true},
    {code: 'sv', name: 'Swedish', flag: 'se', supportsUI: false},
    {code: 'th', name: 'Thai', flag: 'th', supportsUI: false},
    {code: 'tr', name: 'Turkish', flag: 'tr', supportsUI: false},
    {code: 'uk', name: 'Ukrainian', flag: 'ua', supportsUI: true},
    {code: 'vi', name: 'Vietnamese', flag: 'vn', supportsUI: false}
];

export const detectLanguage = (text: string): string | null => {
    if (!text.trim()) return null;
    if (/[\u3040-\u30FF\u4E00-\u9FFF]/.test(text) && /[\u3040-\u30FF]/.test(text)) return 'ja';
    if (/[\uAC00-\uD7AF]/.test(text)) return 'ko';
    if (/[\u4E00-\u9FFF]/.test(text)) return 'zh';
    if (/[\u0600-\u06FF]/.test(text)) return 'ar';
    if (/[\u0900-\u097F]/.test(text)) return 'hi';
    if (/[\u0E00-\u0E7F]/.test(text)) return 'th';
    if (/[\u0590-\u05FF]/.test(text)) return 'he';
    if (/[ыэъё]/i.test(text)) return 'ru';
    if (/[ієїґ]/i.test(text)) return 'uk';
    if (/[а-я]/i.test(text)) return 'ru';
    if (/[ñ¿¡]/i.test(text)) return 'es';
    if (/[łśćżźąę]/i.test(text)) return 'pl';
    if (/[ãõ]/i.test(text)) return 'pt';
    if (/[öäüß]/i.test(text)) return 'de';
    if (/[æøå]/i.test(text)) return 'da';
    return null;
};